### ISSUE TITLE
Action buttons should be grupped under "Actions" button dropdown (Image, Category, Tags and Configuration Manager)

### ISSUE THREAD

**Issue by szepty-ziemi** [JoomGalleryfriends/JG4-dev#11]
Test Env:

PHP Built On: Linux s47.smarthost.pl 4.18.0-348.12.2.lve.el8.x86_64 #1 SMP Mon Jan 24 07:29:58 EST 2022 x86_64
Database Version: 10.3.34-MariaDB
PHP Version: 7.4.28
Web Server: Apache
Joomla! Version: Joomla! 4.1.2 Stable [ Kuamini ] 30-March-2022 16:00 GMT
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0 

Current view in JoomGallery:
![obraz](https://user-images.githubusercontent.com/60470150/161427849-f4156534-571a-4fa1-9116-931606b9ba05.png)

View in Joomla categories:
![obraz](https://user-images.githubusercontent.com/60470150/161427861-99a974ca-3885-49cc-9ee0-dd0a574dbe3e.png)

I guess this discrepancy will be part of functional buttons revamp in future, so this ticket could be expanded with full discrepancies description.

**Comment by szepty-ziemi** [comment]
Issue is also valid for Configuration Manager:

![obraz](https://user-images.githubusercontent.com/60470150/174073567-0b9cea99-7005-47a8-89e7-cd77fe44ea96.png)

**Comment by Elfangor93** [comment]
This issue should be fixed with PR#31.
@szepty-ziemi please confirm and close issue if so.

**Comment by szepty-ziemi** [comment]
Current view (main branch, installed 07.10.2022) looks differently than originally reported. Nevertheless it still looks different than category manager in Joomla. My suggestion is to merge:

- Publish
- Unpublish
- Duplicate
- Delete

Into one, under Action button:

![obraz](https://user-images.githubusercontent.com/60470150/194589192-6148bca3-f1f0-4c14-a7ee-4f9a9913ca3b.png)

Just like in Joomla article categories:

![obraz](https://user-images.githubusercontent.com/60470150/194589277-4e9bb9df-1a6a-42c8-9693-dcfc2864f714.png)

The same apply to Image Manager:

![obraz](https://user-images.githubusercontent.com/60470150/194589590-9ba684c3-504c-4597-8b2d-807841f91b11.png)

And in Joomla articles:

![obraz](https://user-images.githubusercontent.com/60470150/194589654-4983542e-971d-4f38-8d66-b2f7adb13897.png)

The same for Tags:

![obraz](https://user-images.githubusercontent.com/60470150/194589859-a90b3456-c22b-4482-856c-4166ab16af3f.png)

And configuration (which is only partially reorganized):

![obraz](https://user-images.githubusercontent.com/60470150/194590035-271d3402-54ac-429e-aca2-5f15cfc48ad2.png)

**Comment by Elfangor93** [comment]
To be honest - I dont like how it is done in Joomla core: Grouping everything in one dropdown calling it Actions. I would like to group actions in JoomGallery into meaningful Button-Groups. This were the actions we had in JoomGallery 3:

![grafik](https://user-images.githubusercontent.com/39154009/194812862-0d92e689-161d-4672-adb4-dd411ccd7f31.png)

In JoomGallery 4 we could group them into the follwong Dropdowns:
1. Batch-Tools
2. Image manipulations
3. Change state

At this point I would like it different from Core. What do you think?

**Comment by szepty-ziemi** [comment]
Yes, that make sense :) Let's go for it.

**Comment by szepty-ziemi** [comment]
Issue fixed by: https://github.com/JoomGalleryfriends/JG4-dev/pull/46
