### ISSUE TITLE
Error while creating image

### ISSUE THREAD

**Issue by szepty-ziemi** [JoomGalleryfriends/JG4-dev#13]
GIVEN
User is in Image Manager
WHEN
User is clicking NEW button
AND
Enters title for image
AND
Select category Uncategorized
AND
Go to Images tab
AND
Selects image from hard drive
AND
Click SAVE button
THEN
Error is displayed: Return value of Joomgallery\Component\Joomgallery\Administrator\Service\Filesystem\Filesystem::cleanFilename() must be an instance of Joomgallery\Component\Joomgallery\Administrator\Service\Filesystem\mixed, string returned 
BUT
Image should be uploaded and created

![obraz](https://user-images.githubusercontent.com/60470150/161428542-573de80a-508d-4717-8329-1c0718fa9c0a.png)

Test Env:

PHP Built On: Linux s47.smarthost.pl 4.18.0-348.12.2.lve.el8.x86_64 #1 SMP Mon Jan 24 07:29:58 EST 2022 x86_64
Database Version: 10.3.34-MariaDB
PHP Version: 7.4.28
Web Server: Apache
Joomla! Version: Joomla! 4.1.2 Stable [ Kuamini ] 30-March-2022 16:00 GMT
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0 

Tested on PHP 8 and issue do not persist. Seems to be related with PHP 7.4.x only

**Comment by MrMusic** [comment]
>Tested on PHP 8 and issue do not persist. Seems to be related with PHP 7.4.x only

Confirmed. Same with XAMPP and Windows.

**Comment by fontanil** [comment]
Hi,
I met an error on PHP 7.4 trying to add an image: 
`Save failed with the following error: Array`
The error is not the same with PHP 8.0 
`0 in_array(): Argument #2 ($haystack) must be of type array, null given `
File is JROOT\administrator\components\com_joomgallery\src\Service\Uploader\HTMLUploader.php:107 

It's a test site (4.2.0-RC2dev) with new installation of JoomGallery

**Comment by Elfangor93** [comment]
This issue should be fixed with PR#31.
Please confirm @szepty-ziemi and close issue if so.

**Comment by szepty-ziemi** [comment]
Ticket was successfully tested on main branch.
