### ISSUE TITLE
[Filesystem] Warning when upload new image

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#131]
I tried NEW and MULTIPLE NEW and various parameters with ImageMagick.
The result was the same.
All images store correctly.
![Images-New-and-Multiple-New-Screenshot 2023-09-01 212915](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/478ac685-5193-46b8-91e6-9341a16f8d7f)

**I think the reason is PHP 8.1.13. I changed back to 8.0.26 and everything works.**

A total multiple upload of 158 images shows also that this is the reason.
In this case 2 images were failed, but all images have the same warning.
![Screenshot 2023-09-01 215631](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/48c8d5dd-002b-4fa6-b7ff-e5e96cc6ada2)
![Screenshot 2023-09-01 215649](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/3eea6bde-109f-43e2-b5b1-927f4d83823b)

**Comment by MrMusic** [comment]
This PR sould fix the Deprecated warning in the upload form: https://github.com/JoomGalleryfriends/JG4-dev/pull/133

**Comment by AlexanderSupp** [comment]
I changed the PHP options to Joomla recommended values. I installed a fresh JG4 Alpha version. And I got no warning. From my point of view, this issue can be closed.
