### ISSUE TITLE
[UX] Image processing modal

### ISSUE THREAD

**Issue by reilldesign** [JoomGalleryfriends/JG4-dev#135]
General Settings » Image processing (static images)

The popup saves the settings when you close it by clicking x. For a better usability save and cancel buttons would be very helpful.

<img width="800" alt="Bildschirmfoto 2023-09-06 um 14 49 09" src="https://github.com/JoomGalleryfriends/JG4-dev/assets/43771555/b54ac655-b4c1-4a53-99dc-f17d6db34a26">

**Comment by Elfangor93** [comment]
No. The settings are saved when you press the save button in the config edit form view. The popup is just an expansion view of the config edit form view and has by itself no saving capabilities.
Therefore, you close the popup and then press save to save the changes you have made in the popup.
