### ISSUE TITLE
Warning: Invalid argument supplied for foreach() when creating new Configuration set

### ISSUE THREAD

**Issue by szepty-ziemi** [JoomGalleryfriends/JG4-dev#14]
GIVEN
User is in Configuration Manager
AND
Error Reporting is set to Maximum
WHEN
User clicks NEW button
THEN
Warning: Invalid argument supplied for foreach() in /home/siristru/public_html/j4/administrator/components/com_joomgallery/src/Model/ConfigModel.php on line 124 is displayed
BUT
No warning should be displayed.

![obraz](https://user-images.githubusercontent.com/60470150/161428720-1a4550d0-a083-4a66-a428-85882b2e29b9.png)

Test Env:

PHP Built On: Linux s47.smarthost.pl 4.18.0-348.12.2.lve.el8.x86_64 #1 SMP Mon Jan 24 07:29:58 EST 2022 x86_64
Database Version: 10.3.34-MariaDB
PHP Version: 7.4.28
Web Server: Apache
Joomla! Version: Joomla! 4.1.2 Stable [ Kuamini ] 30-March-2022 16:00 GMT
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0

**Comment by Elfangor93** [comment]
@szepty-ziemi This issue should be fixed with PR #21 ...

**Comment by szepty-ziemi** [comment]
VERIFIED
