### ISSUE TITLE
Use real path crashes category-view

### ISSUE THREAD

**Issue by hansdampf-123** [JoomGalleryfriends/JG4-dev#141]
Switching on "Verwende echte Pfade" (use real paths) in Settings crashes frontend in category-view.

Error:
COM_JOOMGALLERY_ERROR_UNSUPPORTED_FILE_TYPE
Call stack
#	Function	Location
1	()	JROOT/administrator/components/com_joomgallery/src/Service/Filesystem/Filesystem.php:701
2	Joomgallery\Component\Joomgallery\Administrator\Service\Filesystem\Filesystem->getUrl()	JROOT/administrator/components/com_joomgallery/src/Helper/JoomHelper.php:452
3	Joomgallery\Component\Joomgallery\Administrator\Helper\JoomHelper::getImg()	JROOT/components/com_joomgallery/tmpl/category/default.php:116
4	include()	JROOT/libraries/src/MVC/View/HtmlView.php:410
5	Joomla\CMS\MVC\View\HtmlView->loadTemplate()	JROOT/libraries/src/MVC/View/HtmlView.php:203
6	Joomla\CMS\MVC\View\HtmlView->display()	JROOT/components/com_joomgallery/src/View/Category/HtmlView.php:95
7	Joomgallery\Component\Joomgallery\Site\View\Category\HtmlView->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:645
8	Joomla\CMS\MVC\Controller\BaseController->display()	JROOT/administrator/components/com_joomgallery/src/Controller/DisplayController.php:118
9	Joomgallery\Component\Joomgallery\Administrator\Controller\DisplayController->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:678
10	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
11	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()	JROOT/components/com_joomgallery/src/Dispatcher/Dispatcher.php:35
12	Joomgallery\Component\Joomgallery\Site\Dispatcher\Dispatcher->dispatch()	JROOT/libraries/src/Component/ComponentHelper.php:361
13	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT/libraries/src/Application/SiteApplication.php:208
14	Joomla\CMS\Application\SiteApplication->dispatch()	JROOT/libraries/src/Application/SiteApplication.php:249
15	Joomla\CMS\Application\SiteApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:293
16	Joomla\CMS\Application\CMSApplication->execute()	JROOT/includes/app.php:61
17	require_once()	JROOT/index.php:32

Joomgallery | 4.0.0-alpha1 Testingrelease
Joomla! Version | 4.3.4
PHP Version | 8.1.23

**Comment by MrMusic** [comment]
Thanks for testing.
Please note: Configuration settings that appear in red are not yet fully implemented and will therefore not work as expected.

**Comment by Elfangor93** [comment]
Will be fixed with PR #224.
