### ISSUE TITLE
Double watermark / watermark not removed

### ISSUE THREAD

**Issue by hansdampf-123** [JoomGalleryfriends/JG4-dev#142]
If the watermark is changed or switched off (in this case I switched it off for thumbnails), the old watermark stays or the new one is added.

Joomgallery     4.0.0-alpha1 Testingrelease
Joomla! Version	4.3.4
PHP Version	8.1.23

**Comment by MrMusic** [comment]
Thanks for testing.
Do use use "fix watermark' oder 'dynamic watermark'? - In JoomGallery 4 is both possible!
Please provide your configuration settings.

**Comment by hansdampf-123** [comment]
I did not add anything to "Bildverarbeitung (dynamische Bilder)" so it should be "statische Bilder"

**Comment by MrMusic** [comment]
If activated in "Image processing (static images)" the watermark is written "fixed" into the image and can of course never be removed!
I would strongly advise to use only the "dynamic" watermark. This can be switched off if necessary.

**Comment by hansdampf-123** [comment]
ok, understood. 
But maybe for the normal user that is not clear. Maybe it could be written (as important) or the standard should be dynamic.
