### ISSUE TITLE
category menu view params

### ISSUE THREAD

**Issue by reilldesign** [JoomGalleryfriends/JG4-dev#143]
I'm trying to access the parameters in the layout file
component/joomgallery/tmpl/category/default.php

For example:
$category_class = $this->params->get('category_class');

But the $category_class is empty. All three new params in the xml file are printed in the url

.../gallery.html?num_columns=3&category_class=masonry&caption_align=left

What is the recommended way to get those params?

**Comment by MrMusic** [comment]
You are trying to access a parameter that you have defined in default.xml file?
You probably have to read the parameter in the HtmlView.php first. Example parameter "spalten":

```
$input  = Factory::getApplication()->input;
$this->params['spalten'] = $input->getInt('spalten', '1');
```

then you can get the parameter in the default.php:

`$countcolumns = $this->params['spalten'];`

Maybe there are other ways?

**Comment by reilldesign** [comment]
This works fine even when the menu alias is called. As long as there is no other recommendation i use this way.

**Comment by Elfangor93** [comment]
In JoomGallery the main configuration parameters are threated with the coniguration service and are set within the configuration sets in the backend or in the params tab of the edit forms of the content types (e.g. images). Besides that you may need to get parameters from the menu item, for example if you have set your own parameters in a template override. Here you find a list of how to get the different coniguration parameters in the view or template files in the frontend:

### Joomla global configuration parameters
The global configuration is set in Backend->System->Global Configuration->System->Global Configuration.
You can get this by using `$this->app->get('sitename', 'Default name', string);`

### Component global configuration parameters
The component global configuration is set in Backend->System->Global Configuration->Component->JoomGallery.
You can get this by using `$this->params['component']->get('inheritance_config', 'default', 'string');`

### Component inherited configuration based on sets
This are the configurations set in the configuration sets in the JoomGallery Backend. They are overritten using the following hierarchy: Menu Item > Image > Category > Custom Configuration Set > Global Configuration Set
Parameters in this config all start with `jg_`.
You can get this by using `$this->params['configs']->get('jg_imagetypes', '', 'string');`

### Menu item configuration parameters
This parameters are set in each menu item and may contain parameters belonging to the components configuration sets. Do not use this approach to get this ones but use the approach explained above. If you want to get menu item parameters that are not threated as configuration set parametern (without `jg_` in the beginning) then you can get this by using `$this->params['menu']->get('page_title', 'Default Title', 'string');`

**Comment by reilldesign** [comment]
@Elfangor93 with `$this->params['menu']` I cannot retrieve my self-defined params. The var_dump lists only the Joomla specific params. With com_content ovverides it is possible to expand the xml and retrieve the params. The goal should be to configure the global Joomgallery settings by each menu item individually.

`var_dump($this->params['menu']);`

object(Joomla\Registry\Registry)#1116 (3) { ["data":protected]=> object(stdClass)#1113 (13) { ["menu-anchor_title"]=> string(0) "" ["menu-anchor_css"]=> string(18) " grid-item--width2" ["menu_icon_css"]=> string(0) "" ["menu_image"]=> string(0) "" ["menu_image_css"]=> string(0) "" ["menu_text"]=> int(1) ["menu_show"]=> int(1) ["page_title"]=> string(0) "" ["show_page_heading"]=> string(0) "" ["page_heading"]=> string(7) "Gallery" ["pageclass_sfx"]=> string(0) "" ["menu-meta_description"]=> string(0) "" ["robots"]=> string(0) "" } ["initialized":protected]=> bool(true) ["separator":protected]=> string(1) "." }

**Comment by Elfangor93** [comment]
>with $this->params['menu'] I cannot retrieve my self-defined params.

Then thats a bug.

**Comment by Elfangor93** [comment]
@reilldesign I just tried it by myself and it works. Here follows a documentation how to do it:

### Menu item configuration parameters

1. Open the xml file of your menu item template
![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/98dbac9e-0919-47f2-93a3-17b0dc010423)

2. Add a new field into the xml file
![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/23c14b8a-d1ad-4451-a211-e127245496fb)

3. Create a new menu item and add a value to your custom menu param. Click save and close.
![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/99b033dd-dbdf-4c8e-8187-420e1a836e94)

4. Access the custom menu param in your template file like the following:
`$this->params['menu']->get('page_title', 'Default Title', 'string');`
![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/964703f7-ccef-4fdc-9261-c5956ec227bd)

5. Check in the frontend that your custom parameter is respected in your chosen template
![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/40479343-fd98-482d-9a17-747262dccc34)

**Comment by Elfangor93** [comment]
Here follows a detail documentation how to use **component inherited configuration parameters** which can be overritten in categories, images and manu items ...

### Component inherited configuration based on sets

1. Select a name for your parameter. The parameter name has to start with `jg_`. In this example I will use `jg_example`.

2. Add at least two language constants for your parameter to the com_joomgallery.ini file of the backend. The name of the language constants has to match with your chosen name.
![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/82910101-0aa3-4280-aded-f200a8080822)

3. Add your parameter to the configuration sets database table by adding a corresponding line to the sql installation file
![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/ea2845d9-08ba-4643-853a-7e47b1f9f39a)

![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/3b3731a3-e2ca-4bba-bae4-2d62b2ebdfb6)
![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/96c86b06-062f-456a-a5f8-06794e163569)

4. Add your parameter to the configuration form xml
![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/b261e4f0-45eb-4c99-87bb-3dbe460e23b6)

![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/82325724-1504-4c0f-a5b2-01262c7ff223)
I want the parameter to be shown in the "Frontend Views" tab and there in the sub tab "Common Settings". Thats why I added the field under the fieldset "fontend" and sub-fieldset "frontend-general". As label and description I used the previously created language constants.

5. At this point you have to uninstall and reinstall the component or to manually add the new column declared in step 3 to the database table `#__joomgallery_configs`.

6. After that you can go to the configuration manager and you will find the new created parameter in the corresponding tabs.
![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/9ea6c731-a117-474d-867b-411c5c40f42b)

7. Access the custom menu param in your template file like the following:
`$this->params['component']->get('jg_example', '', 'string');`
