### ISSUE TITLE
Appearance – language, names, sorting

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#145]
Appearance – language, names, sorting
Whatever can go wrong, will go wrong.
![Screenshot 2023-09-14 214742](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/e6074d46-0a72-4c7e-8a28-e8f614b66b08)
![Screenshot 2023-09-14 214812](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/a127ce17-06e4-4f7a-9202-e45c58f5b798)
![Screenshot 2023-09-14 214926](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/b3351b27-49f9-4e60-bef1-69f279c105a9)
![Screenshot 2023-09-14 214952](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/ab3f6bbd-cf38-46e8-a6dc-6b3dbc068ca6)

From my point of view, a separate function for upload make sense.
But the sort order and the names must be in every language the same.
I'm working on documentation and I'm confused.

**Comment by eumel1602** [comment]
Hello.
1. Do you mean that the “Upload” field is missing in the menu on the left?
2a. That's right, the category and images are swapped in order.
2 B. The second point, that the conficuration is translated differently in German, is my mistake. This will be fixed. I'll leave out the word "manager". / There are other suggestions from you in the forum about the German language, I'll work on them soon... Greetings

**Comment by AlexanderSupp** [comment]
@eumel1602 Take it easy. This issue is more a reminder, what happens if inconsequent software development (here user button) takes place. Without the user buttons in the Control Panel, you have no chance for such mistakes.

**Comment by MrMusic** [comment]
1 Since more upload methods will probably be added, the menu on the left will certainly change. How this will look with these upload methods is not yet known.
2a I will change the ordering of categories and images in the control panel
2b As for the menu and its translations, I would be in favour of always using the 'plural'.

**Comment by MrMusic** [comment]
Fix for 2a: #149

**Comment by AlexanderSupp** [comment]
Issue in the meanwhile obsolete. Therefore, I will close it.
