### ISSUE TITLE
Error notification for PHP 7.2.x contains %s

### ISSUE THREAD

**Issue by szepty-ziemi** [JoomGalleryfriends/JG4-dev#15]
GIVEN
PHP version 7.2 on server
WHEN
Trying to install JoomGallery 4
THEN
Installation is stopped but error notice contains %s "JoomGallery 4.x is only compatible to PHP versions greater than %s"
BUT
Installation is stopped and error notice contains meaningful information

![obraz](https://user-images.githubusercontent.com/60470150/161430287-f923649d-ad1b-49d2-8a99-2f8441e8d2c7.png)

PHP Built On: Linux s47.smarthost.pl 4.18.0-348.12.2.lve.el8.x86_64 https://github.com/JoomGalleryfriends/JG4-dev/pull/1 SMP Mon Jan 24 07:29:58 EST 2022 x86_64
Database Version: 10.3.34-MariaDB
PHP Version: 7.2.34
Web Server: Apache
Joomla! Version: Joomla! 4.1.2 Stable [ Kuamini ] 30-March-2022 16:00 GMT
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0

**Comment by Elfangor93** [comment]
Issue fixed with PR #10 .
