### ISSUE TITLE
Download Link auf www.joomgalleryfriends.net führt zu 404

### ISSUE THREAD

**Issue by csoscd** [JoomGalleryfriends/JG4-dev#150]
Der Download Link auf der Seite https://www.joomgalleryfriends.net/?view=article&id=147:jg-4-0-0-alpha1-testingrelease&catid=33 für die Alpha 1 (https://www.joomgalleryfriends.net/files/joomgallery4/component/JG4-dev-4.0.0-alpha1.zip) führt zu einem 404 Fehler (bzw. der analogen Joomla-Seite).

**Comment by MrMusic** [comment]
Der Link sollte jetzt wieder funktionieren.
Danke für den Hinweis!
