### ISSUE TITLE
Fehler bei der Installation

### ISSUE THREAD

**Issue by csoscd** [JoomGalleryfriends/JG4-dev#151]
**Schritte, um den Fehler reproduzieren zu können**
Joomla 3 (letztes Release) mit deaktivierter JoomGallery 3 auf Joomla 4.3.4 aktualisiert. JoomGallery4 Alpha 1 installiert. Fehlermeldung erhalten. JoomGallery4 Alpha 1 nochmal installiert. Fehlermeldung "Error store default category" erhalten. Dann auf "Start" geklickt, Fehlermeldung erhalten.

**Erwarteted Ergebnis**

Fehlerfreie Installation ;-)

**Tatsächliches Ergebnis**

Fehlermeldungen

**System information**
PHP: 8.2.10
Datenbank: 10.6.12-MariaDB-0ubuntu0.22.04.1
Joomla: Joomla! 4.3.4 Stable

![Fehler3](https://github.com/JoomGalleryfriends/JG4-dev/assets/37827904/6ec70696-12a5-4e4f-b68d-0ee1f9925efa)
[log.txt](https://github.com/JoomGalleryfriends/JG4-dev/files/12742791/log.txt)
![Fehler2](https://github.com/JoomGalleryfriends/JG4-dev/assets/37827904/e2018418-64f9-4b1c-b727-3519bd72708e)

**Comment by MrMusic** [comment]
Das Problem liegt offensichtlich beim Update von der JG3 zur JG4. Aktuell wird das Update in diesem PR entwickelt: [PR #123](https://github.com/JoomGalleryfriends/JG4-dev/pull/123)
Deshalb würde ich empfehlen die Alpha1-Version nur in ein Joomla ohne JoomGallery 3 zu installieren.

**Comment by Elfangor93** [comment]
Das Problem hat nichts mit PR #123 zu tun.
Ich habe das Problem lokalisiert und mit PR #161 gefixt. @csoscd kannst du den upgrade (JG3 -> JG4) mit dem fix nochmals neu probieren?

**Comment by csoscd** [comment]
> Das Problem hat nichts mit PR #123 zu tun. Ich habe das Problem lokalisiert und mit PR #161 gefixt. @csoscd kannst du den upgrade (JG3 -> JG4) mit dem fix nochmals neu probieren?

Ja. Melde mich mit dem Ergebnis.

**Comment by Elfangor93** [comment]
I close this issue, since we have a PR #161 for that.
