### ISSUE TITLE
Aufrufen der Seite zum Anlegen einer neuer Kategorie bringt Fehlerseite

### ISSUE THREAD

**Issue by csoscd** [JoomGalleryfriends/JG4-dev#152]
**Schritte, um den Fehler reproduzieren zu können**
Aufrufen der Seite zum Anlegen einer neuer Kategorie bringt Fehlerseite.

**Erwarteted Ergebnis**
Formular zum Anlegen einer neuen Kategorie.

**Tatsächliches Ergebnis**
Fehlerseite:
![Fehlermeldung](https://github.com/JoomGalleryfriends/JG4-dev/assets/37827904/e28bc142-9ffa-4979-9874-7f4f742458f3)

**System information**
PHP: 8.2.10
Datenbank: 10.6.12-MariaDB-0ubuntu0.22.04.1
Joomla: Joomla! 4.3.4 Stable

Zusätzliche Kommentare

Hängt ggf. mit #151 zusammen?
Die root-Kategorie ist in der Datenbank nicht vorhanden.

**Comment by MrMusic** [comment]
>Hängt ggf. mit https://github.com/JoomGalleryfriends/JG4-dev/issues/151 zusammen?

Ja, sicherlich.
Am besten die alte Joomgallery komplett deinstallieren und von vorne beginnen.

**Comment by csoscd** [comment]
Danke für die Rückmeldung. Werden die Joomla3 Tabellen und auch weitere Daten wie die Bilder im Falle der Deinstallation aus der Datenbank entfernt?

**Comment by MrMusic** [comment]
Ja, bei der Deinstallation werden die Datenbanktabellen und alle JoomGallery-Dateien (einschl. Bilder) entfernt.

**Comment by Elfangor93** [comment]
>Die root-Kategorie ist in der Datenbank nicht vorhanden.

Dies ist das Problem.

>Werden die Joomla3 Tabellen und auch weitere Daten wie die Bilder im Falle der Deinstallation aus der Datenbank entfernt?

Wenn ich das richtig sehe, dann bist du aktuell auf JG4, nach einer gescheitertem upgrade von JG3 zu JG4. Wenn du jetzt JoomGallery deinstallierst, werden alle Tabellen und Bilder-Ordner (`/images/joomgallery`) der JG4 entfernt. Die alten JG3 Tabellen (Tabllen, welche die Endung `_old` haben), sowie Bilder die nicht unter `/images/joomgallery` gespeichert sind, bleiben erhalten.

**Comment by Elfangor93** [comment]
I will close this issue, since it is a result from executing erroreous code during testing which messed up the database. A new fresh Joomla installation fixes the problem.
