### ISSUE TITLE
Categories, Status, Publish subcategory and parent category unpublished -A proper error message is expected.

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#154]
Attempting to publish a subcategory whose parent category is unpublished will result in the error message COM_JOOMGALLERY_N_ITEMS_FAILED_PUBLISHING. A proper error message is expected.

**Comment by Elfangor93** [comment]
This issue is resolved by PR https://github.com/JoomGalleryfriends/JG4-dev/pull/159.
Issue will be closed.
