### ISSUE TITLE
Installstionsfehler

### ISSUE THREAD

**Issue by aleonha1** [JoomGalleryfriends/JG4-dev#156]
Update  auf Joomla 4.3.4 JG Installation bringt Fehler
Table 'kve_joomgallery_old' already exists
![JG-4-Fehler](https://github.com/JoomGalleryfriends/JG4-dev/assets/67064507/8092282b-9f00-4d25-9ac2-8e412b977009)

**Comment by MrMusic** [comment]
War bereits die JoomGallery installiert?
Die Alpha1 solltest du nur in einem Joomla ohne vorhandene JoomGallery testen.

**Comment by aleonha1** [comment]
Ich habe beides probiert. Joomla Gallery 3 deaktiviert; Update auf Joomla 4
[JG4-dev-4.0.0-alpha1_Installation.zip](https://github.com/JoomGalleryfriends/JG4-dev/files/12785711/JG4-dev-4.0.0-alpha1_Installation.zip)

**Comment by aleonha1** [comment]
Nachtrag Fehleranzeige der Ordner struktur (Netbeans)
![JG4-dev-4 0 0-alpha1_4](https://github.com/JoomGalleryfriends/JG4-dev/assets/67064507/87b840cf-e847-4ec7-9212-d2076f1778a6)

**Comment by Elfangor93** [comment]
@aleonha1 Dein Nachtrag hat mit deinem gemeldeten Fehler nichts zu tun.

Deine Fehlermeldung in deinem ersten Post sagt mir, dass du das upgrade schonmal probiert hast. Die gepostete Fehlermeldung ist dann beim zweiten Versuch aufgetreten. Richtig?
Das upgrade kann man bei einem ersten, fehlerhaften Versuch nicht einfach wiederholen. Kann es ein, dass beim ersten Versuche der gleiche Fehler wie bei Issue #151 gekommen ist?

Installiere doch mal PR #161 und versuche das upgrade nochmals mit einer zurückgesetzten (JG3) version.

**Comment by aleonha1** [comment]
Hallo Elfangor,

ich habe die Installation erneut durchgeführt; sieht gut aus 😊
Die alten Bilder sind noch da wie bekomme ich diese in die neue Installation ?
Für einen Tipp wäre ich dankbar


freundliche Grüße

Alfred Leonhardt
Leipziger Straße 19 | 63329 Egelsbach
T:  +49  (0) 6103 946400
M: +49 (0) 171 7839226
F:   +49 (0) 6103 946401 | +49 (0)  322 232 198 16
Mail:      ***@***.******@***.***>



Von: Elfangor ***@***.***>
Gesendet: Donnerstag, 5. Oktober 2023 07:58
An: JoomGalleryfriends/JG4-dev ***@***.***>
Cc: aleonha1 ***@***.***>; Mention ***@***.***>
Betreff: Re: [JoomGalleryfriends/JG4-dev] Installstionsfehler (Issue #156)


@aleonha1<https://github.com/aleonha1> Dein Nachtrag hat mit deinem gemeldeten Fehler nichts zu tun.

Deine Fehlermeldung in deinem ersten Post sagt mir, dass du das upgrade schonmal probiert hast. Die gepostete Fehlermeldung ist dann beim zweiten Versuch aufgetreten. Richtig?
Das upgrade kann man bei einem ersten, fehlerhaften Versuch nicht einfach wiederholen. Kann es ein, dass beim ersten Versuche der gleiche Fehler wie bei Issue #151<https://github.com/JoomGalleryfriends/JG4-dev/issues/151> gekommen ist?

Installiere doch mal PR #161<https://github.com/JoomGalleryfriends/JG4-dev/pull/161> und versuche das upgrade nochmals mit einer zurückgesetzten (JG3) version.

**Comment by Elfangor93** [comment]
> wie bekomme ich diese in die neue Installation ?

Dazu musst fu dich auf alpha 2 der JG4 gedulden. Da wird es ein Migrations-Tool geben.

**Comment by aleonha1** [comment]
Hallo und Danke für die schnelle Rückmeldung
Ihr habt gute Arbeit geleistet!

Alfred

Von: Elfangor ***@***.***>
Gesendet: Donnerstag, 5. Oktober 2023 14:49
An: JoomGalleryfriends/JG4-dev ***@***.***>
Cc: aleonha1 ***@***.***>; Mention ***@***.***>
Betreff: Re: [JoomGalleryfriends/JG4-dev] Installstionsfehler (Issue #156)


wie bekomme ich diese in die neue Installation ?

Dazu musst fu dich auf alpha 2 der JG4 gedulden. Da wird es ein Migrations-Tool geben.

-

**Comment by Elfangor93** [comment]
I close this issue, since we have a PR #161 for that.
