### ISSUE TITLE
[Category] Copy a category does not copy the corresponding image records

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#157]
The marked categories are copied. A category with the addition “(0)” in the name is created at the same category level. The images in the physical file folders are also copied.
The number of images copied with it is not displayed in the category overview. The pictures are also not included in images. However, all images are available in the “details, originals, thumbnails” directories. Now, when I try to delete this orphaned category, I logically get the error message "Category folder named 'categoryname-0' could not be deleted because files and subfolders still exist."

**Comment by Elfangor93** [comment]
When copy a category it successfully copies files and directories, but not the image record in the databse leading to this strange behavior.

**Comment by AlexanderSupp** [comment]
What do we expect if we copy a category?
What happens with the subcategories? Are they copied too?
Make it sense to copy all images to the new categories? 
When will I use a copy function within categories?
Make it sense to duplicate the same images?
In my opinion, it is easier to leave out this copy function because the programming effort is disproportionate to the benefit.
Then we can also close this issue.

**Comment by AlexanderSupp** [comment]
> DE: Ich würde erwarten dass nur der aktuelle Datensatz kopiert wird. Keine Bilder, keine Unterkategorien.

Dann gibt die Funktion (Batch, Duplicate) keinen Sinn, da ich dies auch mit einer Neuanlage erreichen kann.

**Comment by MrMusic** [comment]
>Dann gibt die Funktion (Batch, Duplicate) keinen Sinn, da ich dies auch mit einer Neuanlage erreichen kann.

Nicht ganz: Bei Neuanlage sind alle Felder leer.
Beim Kopieren werden alle bereits vorh. Daten (Titel, Beschreibung, Params...) übernommen.

**Comment by Elfangor93** [comment]
Close this issue since PR https://github.com/JoomGalleryfriends/JG4-dev/pull/179 fixed this issue...
