### ISSUE TITLE
[LANG] Lack of translations in Image Manager - Image Details

### ISSUE THREAD

**Issue by szepty-ziemi** [JoomGalleryfriends/JG4-dev#16]
GIVEN
Editing created image in Image Manager
WHEN
Viewing Images tab
THEN
Untranslated language constants are displayed
BUT
Correct translation should be displayed

List of untranslated constants:

JGLOBAL_FIELDSET_METADATA
COM_JOOMGALLERY_MAIMAN_TYPE_ORIGINAL
COM_JOOMGALLERY_MAIMAN_TYPE_DETAIL
COM_JOOMGALLERY_MAIMAN_TYPE_THUMBNAIL

![obraz](https://user-images.githubusercontent.com/60470150/161431786-7a4f29b5-804d-496c-a334-96209cf9613e.png)

![obraz](https://user-images.githubusercontent.com/60470150/161431801-bf508168-2819-40df-8df5-05d6e2a05d41.png)

![obraz](https://user-images.githubusercontent.com/60470150/161431817-15f2b9bb-f34d-41b0-b96d-7f2b1bd0ec93.png)

![obraz](https://user-images.githubusercontent.com/60470150/161431827-80a3d28e-1bab-4c20-ba13-d0534dfee1ea.png)

![obraz](https://user-images.githubusercontent.com/60470150/161431946-fb5605a7-5e29-422b-9819-3384f3ed00a7.png)

**Comment by Elfangor93** [comment]
This issue should be resolved with PR #31

**Comment by szepty-ziemi** [comment]
The only untranslated language constants are visible in images preview:

![obraz](https://user-images.githubusercontent.com/60470150/188197125-53454217-0a3a-4073-8ca5-7e3285b80543.png)

**Comment by Elfangor93** [comment]
Sorry, correction: This issue should be resolved with PR #34

**Comment by szepty-ziemi** [comment]
I confirm:

![obraz](https://user-images.githubusercontent.com/60470150/188237806-20cdc4db-e4b0-4b67-a4d6-d76a948d4f81.png)

Just for the record, there some other untranslated constants in processing info:

![obraz](https://user-images.githubusercontent.com/60470150/188237902-47db498c-d750-4a5a-9290-19e92bd81dea.png)
