### ISSUE TITLE
Folders of categories are not deleted 

### ISSUE THREAD

**Issue by MrMusic** [JoomGalleryfriends/JG4-dev#162]
When deleting categories, the folders remain in the filesystem.

### Steps to reproduce the issue
Create a category with title 'abc'.
->The category will be created correctly in the database and in the filesystem.

Try to delete the category 'abc'
->The category will be deleted in the database.
->The folders remain in the filesystem

@Elfangor93:
I suspect the error in the function '`getCatPath`' respectively in the '`$this->component->getFilesystem()->cleanPath`' of FileManager.php used there.
**Strange**: 
The function 'getCatPath' returns a corrupt path for **thumbnails**:
'/images/joomgallery/thumbnails\abc' becomes '\images\joomgallery humbnails\abc'.

But for originals and details the path is ok:
'\images\joomgallery\details\abc'
'\images\joomgallery\originals\abc'

### System:
OS: Windows
PHP 8.1
DB: 10.4.27-MariaDB

**Comment by AlexanderSupp** [comment]
Joomla version 5.0. Provider Domain Factory, PHP 8.1, Maria-DB.
I tried to reproduce this issue. So I created a category “ABC”. I added an image. And then I tried to delete the image.
The result was:
![Screenshot 2023-10-30 190832](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/b60fd83d-cce2-48e0-b2c1-3c84ca8fe37d)
But all 3 images were stored in the files correctly.
I tried it a second one with the same result.
All images are stored.
I repeat my test tomorrow.

**Comment by AlexanderSupp** [comment]
I now can confirm the issue. I created a category and after than I deleted this category.
The result in Joomla 5 are below:
![Screenshot 2023-10-31 112338](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/91683ab6-ad93-4e25-977d-c4d2c85fbe7a)

**Comment by Elfangor93** [comment]
Issue is resolved by PR https://github.com/JoomGalleryfriends/JG4-dev/pull/166.
Close this issue.
