### ISSUE TITLE
Installation of JG4-dev-main into Joomla 5.0 failed

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#165]
![Screenshot 2023-10-29 124110](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/2d73e40f-8f39-409b-9119-0cf1adcca81a)
![Screenshot 2023-10-29 125316](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/31e19653-18f4-4d15-a765-070a8e7c7c56)

**Comment by MrMusic** [comment]
Installation problems with Joomla 5 should be solved with PR https://github.com/JoomGalleryfriends/JG4-dev/pull/149.
Currently this PR has not yet been merged into the main branch.
You could try testing this PR with Joomla 5.

**Comment by AlexanderSupp** [comment]
Installation of the component was successful in Joomla 5.0 hosted by my provider.
Now I continue my tests with PR #149.
I close this issue later.

**Comment by AlexanderSupp** [comment]
Everything works fine, and the Control Panel looks good.
