### ISSUE TITLE
empty category

### ISSUE THREAD

**Issue by JochenEb** [JoomGalleryfriends/JG4-dev#168]
I create a new category "Test-05" as well as the subcategories "A", "B", "C".
There are images in the subcategories "A - C", but there are no images in the category "Test-05".
The category "Test-05" is not displayed to me in the category view, even though there are images in the subcategories.
Only when an image is available in the category "Test-05" will the category and the associated subcategories be displayed to me.

Is this a mistake or is it due to the missing backend settings?

![bild2](https://github.com/JoomGalleryfriends/JG4-dev/assets/75810945/b798623c-9b8b-4f05-88f4-5b7a425a7ff7)

**Comment by JochenEb** [comment]
With "List of images" the images are displayed with the subcategory, but not in which category the subcategory is located.
Is it wanted like that?
![bild1](https://github.com/JoomGalleryfriends/JG4-dev/assets/75810945/2113ec14-2136-4f66-962e-2fc3bd0cb5b3)

**Comment by MrMusic** [comment]
>Is this a mistake or is it due to the missing backend settings?

You're right, I've noticed that too. I have submitted a suggestion to change this: https://github.com/JoomGalleryfriends/JG4-dev/pull/169

>With "List of images" the images are displayed with the subcategory, but not in which category the subcategory is located.
Is it wanted like that?

I think 'List of Images' is a default view that was created automatically and it is not sure if this view will stay like this. If so, you would certainly have to make some adjustments.

**Comment by Elfangor93** [comment]
I close this isse since there is a PR #169 for that.
