### ISSUE TITLE
Frontend - Thoughts and discussion about the status at end March 2024 

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#171]
Thoughts about the status and first official release in a nutshell

Joomla Version 5.0.1, 10.4.32-MariaDB, PHP Version 8.1.24
Uninstalling previous JG4 and install actual JG4 main from 22.12.2023
Preparation of Config Sets, Tags, Categories, and images from beginning. 
Everything works fine.

Status at the end of 2023:
Backend is ready for first release of JG4.
Frontend work in progress.

Target group of passive website visitors has priority.
Target group of active website visitors (upload and management of images) later.

Missing module JoomTreeView

The module shows the categories and subcategories of the gallery in the way you know from an explorer showing a filesystem. It gives a quick overview of the total existing categories in the gallery and is ideally suited to quickly and easily navigate between them.

That function is a great help for the first usable release.
Perhaps @erftralle can provide information on how this module can be migrated.

@reilldesign Category View working in progress.
Parameters (Global Value, values per category, values per user?):
Category Layout (Justified, Masonry, Grid Layout)
Title Alignment (None, Left, Center, Right)
Author Alignment (None, Left, Center, Right)
Recording Date (None, Left, Center, Right)
Ideal Height (in pixel)
Gap (in pixel)
Columns (1-6)
Image Layout (None, Boxed)
Sort Table by (...)
Count of Objects per page (5, 10, 15, 20, 25, 30, 50, ..)

Pagination

If I change the Count of Objects in "List of Images", this internal count will adapt for "Category View Justified". Until 25, 30 the images are well present at. Then the next higher is 50 and only max 2 images in one row are presented. But all 50 are displayed.
Grid Layout boxed are OK. Masonry also OK.

All movements within the navigation are carried out correctly. The layout parameters are used in the background and cannot be understood by the administrator or user.

I like @reilldesign idea of using parts of the LightGallery to display individual images in JG4.

I had no problems with Joomla 5.0

I'm looking forward to testing the first functions of migration.

**Comment by AlexanderSupp** [comment]
Now another quarter of a year has passed.
For our next meeting, I suggest defining some of our front-end goals in a little more detail.
Parameters which we want to make available at which place to the administrator for the front end?
Level of Parameters (Global Value, values per category, values per user?):
Category Layout (Justified, Masonry, Grid Layout)
Title Alignment (None, Left, Center, Right)
Author Alignment (None, Left, Center, Right)
Recording Date (None, Left, Center, Right)
Ideal Height (in pixel)
Gap (in pixel)
Columns (1-6)
Image Layout (None, Boxed)
Sort Table by (...)
Count of Objects per page (5, 10, 15, 20, 25, 30, 50, ..)
Pagination
Functions of the Light Gallery
.......

**Comment by Elfangor93** [comment]
Close this issue because it is a pure comment and no work will result from it.
