### ISSUE TITLE
Bildverschiebung bei unterschiedlich langen Bildnamen

### ISSUE THREAD

**Issue by JochenEb** [JoomGalleryfriends/JG4-dev#175]
Hallo,
mit ist bei der aktuellen Git-version (von vor 3 Tagen) aufgefallen, des es bei unterschiedlich langen Bildnamen ggfs. zu Bildverschiebungen kommen kann.
 
https://www.modellheliflieger.de/j4test/index.php/joomgallery-list-of-categories/6-test-04

Gruß
Jochen

**Comment by MrMusic** [comment]
You are using the Masonry layout. There is no uniform "line height" in this layout. This is especially obvious if the height of the images is different.
I would recommend trying the Grid layout.

**Comment by JochenEb** [comment]
Thanks for the feedback.
How can I change the layout to test, there is no setting in the backend.
I'm just testing the versions that I here
https://github.com/ joomgalleryfriends/jg4-dev
find.

**Comment by MrMusic** [comment]
The setting can be set in the respective **menu item**. 
In this case in the tab 'category view'.

**Comment by JochenEb** [comment]
Ah, great. I hadn't seen that yet.
Thanks
