### ISSUE TITLE
[Configs] Change default value for image processing thumbnail

### ISSUE THREAD

**Issue by reilldesign** [JoomGalleryfriends/JG4-dev#181]
All three available category views display landscape and portrait images well in combination. The masonry display only comes into its own when the image is reduced by width. It would be great to change the default setting to by width and 320px. Unfortunately I could not find the corresponding code for a pull request.

![Global-Configuration-Image-Processing-thumbnail](https://github.com/JoomGalleryfriends/JG4-dev/assets/43771555/d3744b46-4f4f-43fc-912c-b4cf1b587db7)

**Comment by MrMusic** [comment]
>It would be great to change the default setting to by width and 320px.

Which is the optimal size is certainly a matter of taste.
For me personally, an ideal height of 200-250px would be better for the Justified layout. But it is certainly depends on the monitor size etc.
DE: Welches die optimale Größe ist, ist sicherlich Geschmacksache.
Für mich persönlich wäre beim Justified layout eine Ideal Height von 200-250px schöner. Ist aber sicherlich abhängig von der Monitorgröße usw.

>Unfortunately I could not find the corresponding code for a pull request.

The default values can be found in script.php. From about line 713 you will find the default values for the respective image type.
DE: Die Default-Werte sind in der script.php zu finden. Etwa ab Zeile 713 findest du für jeden Bild-Typ die Default-Werte (als JSON).

**Comment by AlexanderSupp** [comment]
A resizing by width makes no sense to me. A resizing by height is good for panorama, landscape, and portrait. And here I prefer 250.
However, it's a matter of taste.

**Comment by reilldesign** [comment]
The following pixel widths result for the standard Cassiopeia template within the component area with deactivated boxed view.

Masonry Layout

3 columns = w 418px
4 columns = w 305px 
5 columns = w 240px


Grid Layout

3 columns = w 320px
4 columns = w 305px 
5 columns = w 236px

A width of 250px produces a lower image quality in the vast majority of displays.

Since the 3 column layout is very common i suggest a value between 320px and 380px.

**Comment by AlexanderSupp** [comment]
@reilldesign Thanks for this information. It's good to know something about the internals.

I tested some results of resizing the images.
Keep in mind that I resize not by width. I resize by height!

![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/f02d0dc2-bc87-46eb-af8b-f69cc76b63ed)

As a consequence, I will change my resizing by Height to 380.

**Comment by MrMusic** [comment]
Whether you change by width or by height must actually be decided by each individual and depends on the used layout.
With grid and justified layout, a change according to 'height' would make sense.
With Masonry layout, a change according to 'width' would make sense.
Some meaningful combinations (layout, number of columns, pixels...) could perhaps be made available to users as documentation?

DE: Ob man nach Breite oder nach Höhe ändert muss eigentlich jeder für sich entscheiden und ist vom verwendeten Layout abhängig.
Bei Grid und justified Layout würde m. E. eine Änderung nach 'Höhe' Sinn ergeben.
Beim Masonry layout würde m. E. eine Änderung nach 'Breite' Sinn ergeben.
Einige sinnvolle Kombinationen (Layout, Spaltenzahl, Pixel...) könnte man den Anwendern evtl. in Form einer Doku zur Verfügung stellen?

**Comment by Elfangor93** [comment]
Close issue since the topic was solved in a PR.
