### ISSUE TITLE
[Category view] Display load more button

### ISSUE THREAD

**Issue by reilldesign** [JoomGalleryfriends/JG4-dev#182]
To check whether the load more button should be displayed, I need the total number of category images in the category view.

How can I query this?

**Comment by MrMusic** [comment]
Please take a look into https://github.com/JoomGalleryfriends/JG4-dev/pull/174
I have just added a value for the number of subcategories and the number of images.
Or do you mean something else?

**Comment by reilldesign** [comment]
I need the total number of images in a category to check whether this is greater than the number of images to be displayed.

**Comment by MrMusic** [comment]
Sorry, the total number of images is probably not yet available in the category view. 
Maybe @Elfangor93 can say something about it.

**Comment by Elfangor93** [comment]
No, total number of images is not yet available.

**Comment by Elfangor93** [comment]
This issue is solved with PR #217
