### ISSUE TITLE
Error when using CodeMirror in an updated Joomla

### ISSUE THREAD

**Issue by Elfangor93** [JoomGalleryfriends/JG4-dev#183]
### Steps to reproduce the issue

- Joomla 3.10.x with JoomGallery 3.6.x installed with images and categories
- Update 3.10.x to Joomla 4.4.2
- Update JoomGallery 3.6.x to JoomGallery 4.0.0-dev
- Migrate categories and images using the migration manager of JG4
- Migration configs:
     - Use source ID's: True
     - Use new folder structure: False
     - Image usage: Direct usage
- Open one of the migrated images to edit in the image manager in the backend

### Expected result

Image form opens and changed can be made and saved.

### Actual result
![298075792-f4084721-c591-492b-865e-950c33a6e66d](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/04df3716-5e26-46e9-98ea-e88f498a89ed)

### System information
![298080706-5e120a5d-e9d9-4455-a7d9-1203e31580c1](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/fdaff439-da68-4c7f-b307-99f11146cfdc)

### Additional comments

> Before update to J4, I deinstalled the JCE Editor. After update the preadjustment of standard editor was 'CodeMirror'. So I changed to 'TinyMCE' Editor and could edit the categories (but not yet images). If additionell turn off the plugin 'Editor - CodeMirror', so it is possible also to edit 'images'. (By @rowi68)

@rowi68 Thank you for reporting this issue. Lets see if someone is able to reproduce this issue or if it is something special to your previous Joomla 3 system configuration and plugins.

**Comment by Elfangor93** [comment]
This is the line of code in the codemirror layout (CallStack #3):

````
<?php if ($fsCombo !== '') { ?>
    <p class="small float-end">
        <?php echo Text::sprintf('PLG_CODEMIRROR_TOGGLE_FULL_SCREEN', $fullScreenCombo); ?>
    </p>
<?php }; ?>
````

And thats the one in the Text.php (CallStack #1):

````
// Replace custom named placeholders with sprintf style placeholders
$args[0] = preg_replace('/\[\[%([0-9]+):[^\]]*\]\]/', '%\1$s', $args[0]);
return \call_user_func_array('sprintf', $args);
````

Seems to me as if the error is thrown in `\call_user_func_array('sprintf', $args);` for no obvious reason.

**Comment by Elfangor93** [comment]
The same issue is reported in the hikashop forum:
`https://www.hikashop.com/forum/content-creation/904511-error-at-view-edit-with-php-8.html`

Based on that the bug is related to a wrong language string `PLG_CODEMIRROR_TOGGLE_FULL_SCREEN`.

> However, it seems that the problem stems from the translation key PLG_CODEMIRROR_TOGGLE_FULL_SCREEN which is wrong in a translation file of your website.
Try while logged in in English and you should normally not have the problem, even without removing that line of code. (Source hikashop forum)

@rowi68 Are you using another language else than english? Please switch to english and see if the error is gone. If it is gone, the translation key PLG_CODEMIRROR_TOGGLE_FULL_SCREEN is wrong in the language you are using.

**Comment by rowi68** [comment]
@Elfangor93 Issue solved. You are right. I checked and found the old german language package of J3 was still set. If switch to english the error is gone, also with the actual german language package no problems anymore...
