### ISSUE TITLE
Upload via GD Library needs a lot of memory_limit

### ISSUE THREAD

**Issue by DevelPott** [JoomGalleryfriends/JG4-dev#190]
Joomla: 4.4.2
PHP: 8.1.27
Debug mode: On
Report error: Maximum
memory_limit: 128 MB
Image Processor: GD Library

A lot of memory is required for single and multi uploads.
The upload of a 5MB file returns an error. An entry without an image is still generated.

**But it works with: Image Magick and the setting "Maximum size (in MB)" to 0.**

----

Upload of file 45-20240123.jpg using Uppy failed.

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/vhosts/domain.de/httpdocs/administrator/components/com_joomgallery/src/Service/Filesystem/Filesystem.php on line 831

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/vhosts/domain.de/httpdocs/administrator/components/com_joomgallery/src/Service/Filesystem/Filesystem.php on line 839

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/vhosts/domain.de/httpdocs/administrator/components/com_joomgallery/src/Service/Filesystem/Filesystem.php on line 847

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/vhosts/domain.de/httpdocs/administrator/components/com_joomgallery/src/Service/Filesystem/Filesystem.php on line 831

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/vhosts/domain.de/httpdocs/administrator/components/com_joomgallery/src/Service/Filesystem/Filesystem.php on line 839

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/vhosts/domain.de/httpdocs/administrator/components/com_joomgallery/src/Service/Filesystem/Filesystem.php on line 847

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/vhosts/domain.de/httpdocs/administrator/components/com_joomgallery/src/Service/Filesystem/Filesystem.php on line 831

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/vhosts/domain.de/httpdocs/administrator/components/com_joomgallery/src/Service/Filesystem/Filesystem.php on line 839

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/vhosts/domain.de/httpdocs/administrator/components/com_joomgallery/src/Service/Filesystem/Filesystem.php on line 847

Speichern fehlgeschlagen. Fehler: Filename: 45---20240123.jpg
Upload complete (File-Size: 5629.01 KB)

Imagetype: thumbnail
Used image processor: GD 2.1.0 compatible
Auto-Orientation only possible for JPG files with EXIF orientation meta tag.
Memory limit exceeded. No further processing of the image. Memory requirement: 134 MByte, Serverlimit: 128 MByte. Ask your webhoster for more information.
Image-File (1-1_1_20240208_1865617196.jpg) of type 'thumbnail' could not be created.

Imagetype: detail
Used image processor: GD 2.1.0 compatible
Auto-Orientation only possible for JPG files with EXIF orientation meta tag.
Memory limit exceeded. No further processing of the image. Memory requirement: 142 MByte, Serverlimit: 128 MByte. Ask your webhoster for more information.
Image-File (1-1_1_20240208_1865617196.jpg) of type 'detail' could not be created.

Imagetype: original
Used image processor: GD 2.1.0 compatible
There were some errors in the filesystem. Please check the image folders manually and resolve the problems.
Image-File (1-1_1_20240208_1865617196.jpg) of type 'thumbnail' successfully deleted.
Image-File (1-1_1_20240208_1865617196.jpg) of type 'detail' successfully deleted.
Image-File (1-1_1_20240208_1865617196.jpg) of type 'original' successfully deleted.

----

**Comment by Elfangor93** [comment]
I dont see any issue here. The upload tells you that the creation of thumbnail and detail image does not work with GD since your server does not have enough memory to perfrom the required operations on this image.

You have several possibilities to solve the problem:
- Scale down your image locally before uploading it
- Upgrade your server to have more memory
- Use ImageMagick instead which requires less memory fro the same operations

**Comment by Elfangor93** [comment]
> An entry without an image is still generated.

This is fixed with PR #178.
