### ISSUE TITLE
Migration: Alpha 2 into Joomla 5.0.3 hosting problems

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#201]
To get a feeling for the functionality of a migration with my provider environment, I installed the main from 27.02.2024 14:38.
I'm not sure if my parameters are correct. I ended with  "in_array(): Argument #2 ($haystack) must be of type array, null given". 
Below some screenshots:
![Screenshot 2024-02-27 164423](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/1d9c7b99-52f0-4f36-bf63-2436b949489b)
![Screenshot 2024-02-27 164500](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/0f1b0182-bc7c-464f-b44f-a7b1c11234ad)
![Screenshot 2024-02-27 164532](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/4b2a5f8b-bf84-4c41-93db-8cfbaa78ed6b)
![Screenshot 2024-02-27 164619](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/7115bbb0-e4b3-43ea-98b8-efec38f1dc5f)
![Screenshot 2024-02-27 164637](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/a2c67795-2778-424d-b769-5599198fd81e)

Are my parameters for the source formally correct?
If you like you can have admin rights for this test environment.

**Comment by AlexanderSupp** [comment]
Ich sehe schon, das funktioniert nicht. Ich muss ja localhost angeben.
Aber dann bekomme ich die Meldung "User admin_285146 already has more than 'max_user_connections' active connections " die ich jetzt mit meinem Provider klären muss.

**Comment by AlexanderSupp** [comment]
I changed the host to localhost.
Establish the migration step more than 1 connection?
 "User admin_285146 already has more than 'max_user_connections' active connections"
![Screenshot 2024-02-27 195144](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/889b6f61-fb94-4bda-8d42-30bfda88b3b3)

**Comment by Elfangor93** [comment]
> Are my parameters for the source formally correct?

Most likely the database is not accessible under a public URL. At least the hosting providers I know restrict this. So most probably the entry for host will be localhost.

> "User admin_285146 already has more than 'max_user_connections' active connections"

Whats the value for 'max_user_connections' in your hosting?

**Comment by Elfangor93** [comment]
But if you enter the same `Host`, then it is anyway the same database and `Same database` should not be set to no. Let me think abaout that...

**Comment by AlexanderSupp** [comment]
Now I changed the database username to the same value which I see in the Joomla 3.10.12, "Konfiguration, Server, Datenbank, Benutzer". But I don't know if the password is correct. I was expecting an invalid password error message.
However, now I got the same error as before:
![Screenshot 2024-02-28 123840](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/9a4df7e9-0f6d-44a5-850d-c30f8320f827)
![Screenshot 2024-02-28 123911](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/34ad277e-71e4-4153-89f8-b817493bd54a)

BTW:
Same Joomla installation: Must be no, because I must enter the path of the 3 image-directories.
Same database must be no, because this is really a different database (i. e. with my categories) which I must enter.
I started a request to my provider.
My databases:
![Screenshot 2024-02-28 130041](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/22dfd1da-1280-4366-a7dd-5270ac004fee)
My Joomla installations:
![Screenshot 2024-02-28 130157](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/0f226cd9-c29b-462f-9910-8460b2169a17)

**Comment by Elfangor93** [comment]
> I was expecting an invalid password error message

No. Currently there is nothing coded to check the database credentials. If it is set wrong, the code will fail at one point and trow a php error.

**Comment by eumel1602** [comment]
Grundsätzlich gefragt. Wie ist den der richtige Pfad unter "joomla path" ? (Das muss noch in die Erklärung rein!)
Ich habe den selben Fehler wie im ersten Kommentar von alexander. 
Beispiele für pfade: 
https://www.meinewebadresse.de/testinstallation
oder:
www.meinewebadresse.de/testinstallation
oder:
meinewebadresse.de/testinstallation
?
Bei mir funktionieren alle drei nicht

**Comment by AlexanderSupp** [comment]
Schau mal hier, was da bei dir steht. Nachstehend mein Provider:
![Screenshot 2024-02-28 163159](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/8db6058c-f13b-49cd-a19c-44595bdf7546)

Bei den Dateien in den Verzeichnissen, also den Bildern, kannst du den Vorspann für images ausgehend vom root path für "/images/joomgallery/original" herausfinden. Unter Win 11 sieht das dann so aus: C:/wamp64/www/FotofreundeMuch/
Wobei:
Complete system path to the Joomla! root directory of the source. More...
Use forward slash (/) as directoy separator. No slash at the end of the path.
ich am Ende doch ein / gesetzt habe.

**Comment by eumel1602** [comment]
auch mit diesem Pfad funktioniert das nicht. Fehler bleibt gleich. ist sicher was, das der provider das nicht zuläßt.

**Comment by MrMusic** [comment]
If you are working locally, e.g. with XAMPP under Windows, the path could look like this
C:\xampp\htdocs\folder-of-the-old-page

If you are working on a "real" server on the Internet, the path could look like this, for example
/homepages/17/a12345678/htdocs/folder-of-the-old-page

As @AlexanderSupp has already written:
It would be helpful to look into the configuration of the old Joomla. If you look at the path to the log or temp directory, you can read out the path (omit the /administrator/logs or /tmp at the end).

The same applies to accessing the database:
In the Joomla configuration in the tab Server the data is in there, if necessary you can also read it out of the configuration.php.

What certainly does not work: Trying to access the data from a page on the Internet from a local installation.

DE:
Wenn du lokal, z.B. mit XAMPP unter Windows arbeitest, könnte der Pfad so aussehen:
C:\xampp\htdocs\ordner-alte-seite

Wenn du auf einem "richtigen" Server im Internet arbeitest, könnte der Pfad z.B. so aussehen:
/homepages/17/a12345678/htdocs/ordner-alte-seite

Wie Alexander schon geschrieben hat:
Hilfreich wäre in die Konfiguration des alten Joomlas zu schauen. Wenn du den Pfad zum Log- bzw. Temp-Verzeichnis ansiehst, kannst du den Pfad rauslesen (das /administrator/logs bzw. /tmp am Schluss weglassen).

Das gleiche für den Zugang zur Datenbank:
In der Joomla-Konfiguration im Tab Server stehen die Daten drin, kann man notfalls auch aus der configuration.php auslesen.

Was sicherlich nicht funktioniert: In einer lokalen Installation auf die Daten von einer Seite im Internet zugreifen zu wollen.

**Comment by eumel1602** [comment]
danke für eure versuche mir zu helfen.
anbei bein bildschirm:

![bildschirmabgriff](https://github.com/JoomGalleryfriends/JG4-dev/assets/96334985/cfd531e1-2a33-4450-9d1f-30d7b3f8ba6e)

**Comment by MrMusic** [comment]
Wenn der Fehler 
_0 in_array(): Argument #2 ($haystack) must be of type array, null given_ 
erscheint, liegt dass höchstwahrscheinlich falschen Zugangsdaten zur Datenbank.

**Comment by MrMusic** [comment]
>Can the "Host" for the database really be "localhost" for an online migration?

Yes, if the database is hosted on the same server. This is often the case.

**Comment by AlexanderSupp** [comment]
**Hinweis: Beachte auch die Angaben deines Providers.**
Zum Beispiel für SQL-Server:
Hostname für MariaDB =     localhost
Hostname für MySQL   =     mysql

**Comment by eumel1602** [comment]
also bei mir ist der Hostname für eine MySQLi Datenbank: "localhost"

**Comment by Elfangor93** [comment]
I have successfully reproduced the error reported by @AlexanderSupp.
![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/1899b7da-0908-4929-b3be-aeaf8bbc9e4c)

It seems that the migration precheck requires 20 user connections to the database in order to work. I am looking into the reason for that...

**Comment by AlexanderSupp** [comment]
Oh, how nice that we have our fox Manuel, who successfully detects all the inconsistencies.
Thank you very much. I'll test that right away.

**Comment by AlexanderSupp** [comment]
From my point of view, this issue is solved with the last tests. Therefore, will close this issue.
