### ISSUE TITLE
Error display after installing JG 3.7.0rc1

### ISSUE THREAD

**Issue by eumel1602** [JoomGalleryfriends/JG4-dev#202]
Immer wenn ich oben genannte version installiere kommt der folgende bildschirm. mit einem "503" Info. Die Installation scheint aber zufunktionieren:

![bildschirmabgriff](https://github.com/JoomGalleryfriends/JG4-dev/assets/96334985/8a1baf1d-8a29-4ae4-8bcf-e33e7671a71b)

Ist die 3.7.0rc-1 installiert, zeigt es im adminbereich der Gallery **ganz unten aber überall noch die Version 3.6.2**. an

**Comment by AlexanderSupp** [comment]
Habe ebenfalls diese Meldung.
Kann es sein, dass die Meldung immer dann kommt, wenn diese Funktion schon einmal installiert war?
Ich hatte ja die Funktion aus dem PR schon installiert.
Und ja, der eindeutige Text oben passt nicht zur Version unten.
So, what?

![Screenshot 2024-03-02 123325](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/9a9144c4-293c-4d7b-96de-518fc390db2f)
![Screenshot 2024-03-02 123348](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/3e43df2b-6066-4271-90c6-16c8937a1d23)

**Comment by MrMusic** [comment]
>Ist die 3.7.0rc-1 installiert, zeigt es im adminbereich der Gallery ganz unten aber überall noch die Version 3.6.2. an

Das ist (leider) ein bekanntes Problem, wenn man das Zip im Erweiterungs-Manager manuell hochlädt.
Einmal ausloggen und wieder einloggen in Joomla zeigt dann die richtige Version an.

**Comment by eumel1602** [comment]
> > Einmal ausloggen und wieder einloggen in Joomla zeigt dann die richtige Version an.

Ok. Das hatte ich versucht bzw dachte ich das auch aber es bleibt. Hängt aber mit dem cache zusammen, den gelöscht und es zeigt die richtige Version an!

**Comment by Elfangor93** [comment]
@eumel1602 Can we close this issue or do you want something to be done about that?

**Comment by eumel1602** [comment]
@Elfangor93  das kann geschlossen werden!
