### ISSUE TITLE
[Jg3ToJg4] migration fails if images are present without originals

### ISSUE THREAD

**Issue by florianrosenauer** [JoomGalleryfriends/JG4-dev#204]
Testsystem: Windows 10, xampp-8-0-30 (default config plus GD enabled)
Followed exaxtly the guide from https://www.youtube.com/watch?v=7zznRGVcU6k (except that I ignore non-joomgallery-compatibility issues as I did test only the joomgallery migration).

We have about 5000 images in our installation, where about 200 do not have the original files. I think there is/was a setting to prevent the originals to be stored to save disk space which was important back in 2005. The Maintenance Manager shows them in the list like here:
![Migration-Try02-migr00a_cropped](https://github.com/JoomGalleryfriends/JG4-dev/assets/5151028/3e7f8f86-49c9-406b-bc89-653e19807ce9)

Migration Settings:
![Migration-Try01-migr01](https://github.com/JoomGalleryfriends/JG4-dev/assets/5151028/4dfa816e-859a-4366-b68f-b2367bf6ddbc)

With this setup, the migration fails with these error messages:
```
[Success] [Migrator.js] Migration of image with id = 4076 successful.

[Success] [Migrator.js] Migration of image with id = 4077 successful.

[Success] [Migrator.js] Migration of image with id = 4078 successful.

[Error] [Migrator.js] Migration of image with id = 4114 failed.

[Error] Error in creating imagetypes. See log file for more details.

[Info] Image-File (XXX_2014_20140112_2076869220.jpg) of type 'original' could not be copied.

[Info] Image-File (XXX_2014_20140112_2076869220.jpg) of type 'thumbnail' successfully deleted.

[Info] Image-File (XXX_2014_20140112_2076869220.jpg) of type 'detail' successfully deleted.

[Info] Image-File (XXX_2014_20140112_2076869220.jpg) of type 'original' successfully deleted.

[Error] [Migrator.js] Migration of image with id = 4115 failed.

[Error] Error in creating imagetypes. See log file for more details.

[Info] Image-File (XXX_2014_20140112_1003638096.jpg) of type 'original' could not be copied.

[Info] Image-File (XXX_2014_20140112_1003638096.jpg) of type 'thumbnail' successfully deleted.

[Info] Image-File (XXX_2014_20140112_1003638096.jpg) of type 'detail' successfully deleted.

[Info] Image-File (XXX_2014_20140112_1003638096.jpg) of type 'original' successfully deleted.

[Error] [Migrator.js] Migration of image with id = 4116 failed.

[Error] Error in creating imagetypes. See log file for more details.

[Info] Image-File (XXX_2014_20140112_1220844819.jpg) of type 'original' could not be copied.

[Info] Image-File (XXX_2014_20140112_1220844819.jpg) of type 'thumbnail' successfully deleted.

[Info] Image-File (XXX_2014_20140112_1220844819.jpg) of type 'detail' successfully deleted.

[Info] Image-File (XXX_2014_20140112_1220844819.jpg) of type 'original' successfully deleted.

```

and does not continue after these three failed ones.

Expected: Migration does not fail.

Workaround: I copied the "details" images for all categories without originals into the originals folder, then the migration works witout problems.

PS: Further Improvement Idea: the error messages about the deleted images are a bit misleading, as the files were not deleted, at least not the Joomgallery 3.x files. Maybe the already copied files, but it would be nice to make that more clear from where something was deleted.

**Comment by MrMusic** [comment]
Thanks for your Tests!
>and does not continue after these three failed ones.

As a test, I deleted 4 original images in my installation and started the migration. With the exception of these 4 images, it ran through to the end.
In your case it was stopped after 3 images?
Is the message as shown in the screenshot really the last message or did another problem occur afterwards?

**Comment by florianrosenauer** [comment]
Yes, it stopped after three failed images, I tried two more times (1x on xampp, 1x on my webhoster on a page duplicate), it stops always at the same image:
![Migration-Try03-(HWGost)-migr-JoomGalleryError](https://github.com/JoomGalleryfriends/JG4-dev/assets/5151028/104d9619-14a9-4cb5-85d9-746883f83478)

Every time I click on "Start migration" afterwards, it tries one more image (next ID, same error), and increases the failed count by 2.

**Comment by MrMusic** [comment]
Can you please test it with this PR?: https://github.com/JoomGalleryfriends/JG4-dev/pull/214
The script should not stopped due to the missing originals.
