### ISSUE TITLE
Warning messages during upload

### ISSUE THREAD

**Issue by MrMusic** [JoomGalleryfriends/JG4-dev#206]
Nothing dramatic, but there are a few new messages.
Test:
Joomla 5.0.3
PHP 8.1
Error reporting: Maximum
Multiple upload
Debug mode: Yes
The following message appears seven times in the debug output:

_Notice: Attempting to set reference to non referenceable value in ...\plugins\system\joomowner\src\Extension\JoomgalleryOwner.php on line 210
Warning: Undefined array key 0 in ...\plugins\system\joomowner\src\Extension\JoomgalleryOwner.php on line 210
Notice: Attempting to set reference to non referenceable value in ...\plugins\system\joomowner\src\Extension\JoomgalleryOwner.php on line 210
Warning: Undefined array key 1 in ...\plugins\system\joomowner\src\Extension\JoomgalleryOwner.php on line 210
Warning: Undefined array key 2 in ...\plugins\system\joomowner\src\Extension\JoomgalleryOwner.php on line 210
Warning: Undefined array key 3 in ...\plugins\system\joomowner\src\Extension\JoomgalleryOwner.php on line 210
Notice: Only variables should be assigned by reference in ...\plugins\system\joomowner\src\Extension\JoomgalleryOwner.php on line 215_

**Comment by Elfangor93** [comment]
I can not fix this warnings and notices without breaking the Joomla 4 compatibility.
