### ISSUE TITLE
[Jg3ToJg4] Data too long for column 'queue'

### ISSUE THREAD

**Issue by buschmann23** [JoomGalleryfriends/JG4-dev#208]
I am trying to migrate a JG3 installation with 15,793 images in 295 categories. Migrating the categories worked, but when pressing `Start migration` for the images, nothing happens. The log file shows the following error:

```
2024-03-07T16:18:46+00:00       ERROR 127.0.0.1 com_joomgallery Data too long for column 'queue' at row 1
```

The JG3 installation is on the same Joomla instance and I followed the instructions from the YouTube video on how to migrate.

Web server: Apache 2.4.58
PHP: 8.2.16
MariaDB: 11.2.3

**Comment by buschmann23** [comment]
Upps, ja, die Joomla-Version hatte ich vergessen: 4.4.3

Kann ich die Menge der zu importierenden Bilder irgendwo begrenzen oder müsste ich zum Testen ein neue Instanz mit weniger Bildern anlegen?

**Comment by MrMusic** [comment]
If you are familiar with phpMyAdmin you can try to change the **type** of the following columns in the table #__joomgallery_migration:
Column _queue_ from **text** -> **longtext**
Column _successful_ from **text** -> **longtext**
Column failed from **text** -> **longtext**
You can then test the migration again with a large number of images.

DE: Wenn du dich mit phpMyAdmin etwas auskennst, kannst du versuchen in der Tabelle #__joomgallery_migration den Typ folgender Spalten zu ändern:
Spalte queue von **text** -> **longtext**
Spalte successful von **text** -> **longtext**
Spalte failed von **text** -> longtext
Anschließend kannst du die Migration mit sehr vielen Bildern testen.

**Comment by buschmann23** [comment]
👍🏻 Changing the column types from text to longtext fixed it.

**Comment by MrMusic** [comment]
I have created a pull request to fix this problem: https://github.com/JoomGalleryfriends/JG4-dev/pull/214
