### ISSUE TITLE
Change of the 'Image types' names in comparison to JoomGallery 3.x

### ISSUE THREAD

**Issue by MrMusic** [JoomGalleryfriends/JG4-dev#213]
To display a JoomGallery 3 image in a Joomla article, for example, the following has been placed in the IMG tag:
For example the Thumbnail:
`src="index.php?option=com_joomgallery&amp;view=image&amp;format=raw&amp;id=123&amp;type=thumb"`
Detail image:
`src="index.php?option=com_joomgallery&amp;view=image&amp;format=raw&amp;id=123&amp;type=img"`
Original image:
`src="index.php?option=com_joomgallery&amp;view=image&amp;format=raw&amp;id=123&amp;type=orig"`

In JoomGallery 4 the types have been changed:
src="index.php?option=com_joomgallery&amp;view=image&amp;format=raw&amp;id=123&amp;type=**thumbnail**
src="index.php?option=com_joomgallery&amp;view=image&amp;format=raw&amp;id=123&amp;type=**detail**
src="index.php?option=com_joomgallery&amp;view=image&amp;format=raw&amp;id=123&amp;type=**original**

Due to this name change, after a migration from JG3 the images are no longer displayed in articles.

DE: Änderung der 'Image types' Bezeichnung gegenüber der JoomGallery 3.x
Zur Anzeige eines Bildes der JoomGallery 3 in z.B. in einem Joomla Beitrag, wurde folgendes in das IMG Tag eingesetzt:
Für das Thumbnail beispielsweise:
`src="index.php?option=com_joomgallery&amp;view=image&amp;format=raw&amp;id=123&amp;type=thumb"`
Detailbild:
`src="index.php?option=com_joomgallery&amp;view=image&amp;format=raw&amp;id=123&amp;type=img"`
Originalbild:
`src="index.php?option=com_joomgallery&amp;view=image&amp;format=raw&amp;id=123&amp;type=orig"`

In JoomGallery 4 haben sich die 'types' geändert:
src="index.php?option=com_joomgallery&amp;view=image&amp;format=raw&amp;id=123&amp;type=**thumbnail**
src="index.php?option=com_joomgallery&amp;view=image&amp;format=raw&amp;id=123&amp;type=**detail**
src="index.php?option=com_joomgallery&amp;view=image&amp;format=raw&amp;id=123&amp;type=**original**

Durch diese Namensänderung werden nach einer Migration von der JG3 keine Bilder in Beiträgen mehr angezeigt.

**Comment by Tazzios** [comment]
i`m not sure or it is useful but here some SQL that could do the replacements:

Article content
```
UPDATE #__content
SET 

	/*replace firstpart of url*/
	`introtext` = REPLACE(introtext, '&amp;view=image&amp;format=raw&amp;id=', '&view=image&format=raw&id=')
	`FULLTEXT` = REPLACE(FULLTEXT, '&amp;view=image&amp;format=raw&amp;id=', '&view=image&format=raw&id=')	
	`images` = REPLACE(images, '&amp;view=image&amp;format=raw&amp;id=', '&view=image&format=raw&id=')	

	/* replace secondpart of url*/
	`introtext` = REPLACE(introtext, '&amp;type=thumb', '&type=thumbnail'),	
	`introtext` = REPLACE(introtext, '&amp;type=img', '&type=detail'),
	`introtext` = REPLACE(introtext, '&amp;type=orig', '&type=original')		

	`FULLTEXT` = REPLACE(FULLTEXT, '&amp;type=thumb', '&type=thumbnail'),
 	`FULLTEXT` = REPLACE(FULLTEXT, '&amp;type=img', '&type=detail'),
 	`FULLTEXT` = REPLACE(FULLTEXT, '&amp;type=orig', '&type=original')
 	
	`images` = REPLACE(images, '&amp;type=thumb', '&type=thumbnail'),
 	`images` = REPLACE(images, '&amp;type=img', '&type=detail'),
 	`images` = REPLACE(images, '&amp;type=orig', '&type=original') 	
WHERE 
  `introtext` LIKE '%&amp;type%' 
  OR `fulltext` LIKE '%&amp;type%'
  OR `images` LIKE '%&amp;type%'


```

Custom modules
```
UPDATE #__modules
SET
	/*replace firstpart of url*/
	`content` = REPLACE(content, '&amp;view=image&amp;format=raw&amp;id=', '&view=image&format=raw&id=')	

	/* replace secondpart of url*/
	`content` = REPLACE(content, '&amp;type=thumb', '&type=thumbnail'),	
	`content` = REPLACE(content, '&amp;type=img', '&type=detail'),
	`content` = REPLACE(content, '&amp;type=orig', '&type=original')	

WHERE 
	`module` = 'mod_custom' 
	AND  `content` LIKE '%&amp;type%' 
```
