### ISSUE TITLE
JG 4.0.0 Beta2 / PHP 8.2.6 Deprecated messages when opening "Global Configuration"

### ISSUE THREAD

**Issue by jobrusche** [JoomGalleryfriends/JG4-dev#216]
Running on  Wampserver 3.3 with PHP 8.2.6 / Joomla 5.0.3

From JoomGallery menu, use Configuration Sets, click on "Global configuration"
Several pages of Deprecated messages are displayed.

When switching back to PHP 8.1.26, all these messages are gone.

Example of messages:

Deprecated: Creation of dynamic property
Joomgallery\Component\Joomgallery\Administrator\Service\Config\DefaultConfig::$jg_compatibility_mode is deprecated in D:\wamp64\www\myjoom5\administrator\components\com_joomgallery\src\Extension\ServiceTrait.php on line 114

Deprecated: Creation of dynamic property Joomgallery\Component\Joomgallery\Administrator\Service\Config\DefaultConfig::$jg_checkupdate is deprecated in D:\wamp64\www\myjoom5\administrator\components\com_joomgallery\src\Extension\ServiceTrait.php on line 114

Deprecated: Creation of dynamic property Joomgallery\Component\Joomgallery\Administrator\Service\Config\DefaultConfig::$jg_replaceinfo is deprecated in D:\wamp64\www\myjoom5\administrator\components\com_joomgallery\src\Extension\ServiceTrait.php on line 114

Deprecated: Creation of dynamic property Joomgallery\Component\Joomgallery\Administrator\Service\Config\DefaultConfig::$jg_replaceshowwarning is deprecated in D:\wamp64\www\myjoom5\administrator\components\com_joomgallery\src\Extension\ServiceTrait.php on line 114

Deprecated: Creation of dynamic property Joomgallery\Component\Joomgallery\Administrator\Service\Config\DefaultConfig::$jg_useorigfilename is deprecated in D:\wamp64\www\myjoom5\administrator\components\com_joomgallery\src\Extension\ServiceTrait.php on line 114

Deprecated: Creation of dynamic property Joomgallery\Component\Joomgallery\Administrator\Service\Config\DefaultConfig::$jg_uploadorder is deprecated in D:\wamp64\www\myjoom5\administrator\components\com_joomgallery\src\Extension\ServiceTrait.php on line 114

 Deprecated: Creation of dynamic property Joomgallery\Component\Joomgallery\Administrator\Service\Config\DefaultConfig::$jg_filenamenumber is deprecated in D:\wamp64\www\myjoom5\administrator\components\com_joomgallery\src\Extension\ServiceTrait.php on line 114

Deprecated: Creation of dynamic property Joomgallery\Component\Joomgallery\Administrator\Service\Config\DefaultConfig::$jg_parallelprocesses is deprecated in D:\wamp64\www\myjoom5\administrator\components\com_joomgallery\src\Extension\ServiceTrait.php on line 114

 Deprecated: Creation of dynamic property Joomgallery\Component\Joomgallery\Administrator\Service\Config\DefaultConfig::$jg_imgprocessor is deprecated in D:\wamp64\www\myjoom5\administrator\components\com_joomgallery\src\Extension\ServiceTrait.php on line 114

Deprecated: Creation of dynamic property Joomgallery\Component\Joomgallery\Administrator\Service\Config\DefaultConfig::$jg_fastgd2creation is deprecated in D:\wamp64\www\myjoom5\administrator\components\com_joomgallery\src\Extension\ServiceTrait.php on line 114

This is not the full list of messages..

**Comment by Elfangor93** [comment]
>Deprecated: Creation of dynamic property
Joomgallery\Component\Joomgallery\Administrator\Service\Config\DefaultConfig::$jg_compatibility_mode is deprecated in D:\wamp64\www\myjoom5\administrator\components\com_joomgallery\src\Extension\ServiceTrait.php

Will be fixed with PR #211
