### ISSUE TITLE
Joomla 5.1.0 Modalfenster der JG PR's gehen nicht mehr auf 

### ISSUE THREAD

**Issue by eumel1602** [JoomGalleryfriends/JG4-dev#220]
Nach dem update von Joomla auf 5.1. funktionieren in der JG 4 (egal welchen PR ich versuche) die Modalfenster nicht mehr. sie gehen nicht mehr auf!
**Kann das mal jemand testen?** 
PHP 8.2.

(In J! 4.4.4 läuft es)
![1](https://github.com/JoomGalleryfriends/JG4-dev/assets/96334985/0bd085ea-4275-4b10-a3f6-e95b3ae90f29)

**Comment by MrMusic** [comment]
I can confirm the error with modals in Joomla 5.1
DE:
Ich kann den Fehler bestätigen.

**Comment by mac-joomla** [comment]
Mit PR #225 funktioniert es wieder. Danke!
