### ISSUE TITLE
JG 4: Call to undefined function exec()

### ISSUE THREAD

**Issue by sabersaberi2** [JoomGalleryfriends/JG4-dev#221]
hi.
when i want to open the config Global Configuration i get the:
Call to undefined function exec()

yes i understand hosting must access to this function of PHP but they prevent to access that for security reason.
i understand maybe you say it is problem of your hosting but i report that to you too.

**Comment by MrMusic** [comment]
Yes, i can confirm this problem.
There should only be a hint and no PHP error.
I will create a PR for this.

**Comment by MrMusic** [comment]
>könnt ihr noch kurz genauer erklären was das für ein wert ist? kann das sein das ich den in den experteneinstellungen bei meinem Hoster nicht verändern kann? geht das nur lokal? (Hoster alfahosting)

Einfach ausgedrückt: Mit "exec" kann man eigenständige Programme starten die auf dem Server liegen. Ansonsten kann z.B. ImageMagick nicht genutzt werden.
Um 'exec' zu verbieten, muss man die Liste der '_disable_functions_' in der php.ini entsprechend erweitern, z.B. so: `disable_functions="shell_exec, exec"`
Ob dein Hoster die Bearbeitung dieser Zeile zulässt, kann ich nicht einschätzen (kenne ihn nicht).
Bei einer lokalen Installation kannst du einfach die php.ini bearbeiten.

**Comment by eumel1602** [comment]
Ich habe bei meinem provider "exec" abstellen lassen. dann den main brunch installiert, Beim klicken auf die JG 4 confic kommt kein Fehler. 
Kann also den Fehler leider nicht nachstellen bzw den dazugehörigen PR testen...
J 4.4.4. PHP 8.1

**Comment by eumel1602** [comment]
Komando zurück. Natürlich kam der Fehler, so konnte ich nun das Problem nachstellen und den PR testen.
Keine ahnung was sich da aufgehangen hatte. manchmal soll man einfach nochmal von vorne anfangen. 
@sabersaberi2 danke fürs melden

**Comment by Elfangor93** [comment]
Fixed with PR #222
