### ISSUE TITLE
Fehler mit aktiviertem System-JoomGallery Plugin

### ISSUE THREAD

**Issue by mac-joomla** [JoomGalleryfriends/JG4-dev#226]
JoomGallery Version: 4.0.0-dev und Joomla 5.1.0 und PHP 8.2.18

Wenn das System-JoomGallery Plugin aktiviert ist bekommt man bei folgenden Tätigkeiten im Backend

• System > Site Template Stile > Dann alternatives Template zum Standard machen
• System > Updates > Erweiterungen > Auf Updates prüfen
• System > Einstellungen > Konfiguration > Speichern

den folgenden Fehler. Bei deaktiviertem Plugin tritt der Fehler nicht auf.

Es ist ein Fehler aufgetreten.
0 Joomla\CMS\Event\Model\AfterCleanCacheEvent::onSetResult(): Argument #1 ($value) must be of type bool, array given, called in /joomla-root-verzeichnis/libraries/src/Event/AbstractEvent.php on line 227

**Comment by MrMusic** [comment]
Danke, das kann ich bestätigen. Mit Joomla 5.1 tritt dieses Problem auf.
