### ISSUE TITLE
Fehler beim zurücksetzen der Globalen Konfiguration

### ISSUE THREAD

**Issue by mac-joomla** [JoomGalleryfriends/JG4-dev#227]
Backend > Komponenten > JoomGallery >  Konfigurations-Manager > Global Configuration > Zurücksetzen Button in der oberen Button Leiste betätigen und die Warnung mit Ja bestätigen

Man bekommt dann den folgenden Fehler:

Es ist ein Fehler aufgetreten.
1 Config field with name jg_category_view_subcategory_image_class does not have any default value!

**Comment by MrMusic** [comment]
@mac-joomla Danke für die Meldung.
Ich werde dafür einen PR erstellen.
