### ISSUE TITLE
Speichern von Frontend Ansichten in der Konfiguration nicht möglich

### ISSUE THREAD

**Issue by mac-joomla** [JoomGalleryfriends/JG4-dev#228]
JoomGallery Version: 4.0.0-dev und Joomla 5.1.0 und PHP 8.2.18

In den folgenden beiden Bereichen werden geänderte Voreinstellungen nicht gespeichert, wenn man den Speichern Button klickt:

Backend > Joomgallery > Konfigurations-Manager > Global Configuration > Frontend Ansichten > Category View und Single Image View

**Comment by eumel1602** [comment]
das kann ich "leider" nicht bestätigen. Unter J 5.1.1 und php 8.2.5 kann man da alles speichern?!

**Comment by MrMusic** [comment]
Mit der Alpha3 Version sollte es keine Probleme geben. Vor einer Installation müsstest du aber deine vorherige JG4 Version deinstallieren, da ansonsten wichtige Datenbankänderungen fehlen.
