### ISSUE TITLE
Handling of duplicate image titles after migration

### ISSUE THREAD

**Issue by hansdampf-123** [JoomGalleryfriends/JG4-dev#232]
Migrated from Jommla 3 to Joomla 4 and then 5
Update/Migration to JG 4alpha2

Several Images with the same title now have a (2), (3) and so on behind it. 
sample 1
title in JG3 Mittelalterschert
alias in JG 3 mittelalterschwert-3440
title in JG4 Mittelalterschwert
alias in JG 4 mittelalterschwert

sample 2
title in JG3 Mittelalterschert
alias in JG 3 mittelalterschwert-3441
title in JG4 Mittelalterschwert (2)
alias in JG 4 mittelalterschwert-2

The IDs are the same after the migration, but the aliases have been renewed without the id. I don't know at what step, put it was not done on purpose / automatically. That leads two potential duplicates, which is solved by the added numbers.

**Comment by Elfangor93** [comment]
Whats the issue here?
@MrMusic Is it normal that aliases in old JG versions have the ID appended? This is new to me.

**Comment by MrMusic** [comment]
>@MrMusic Is it normal that aliases in old JG versions have the ID appended? This is new to me.

Yes, for images the ID was appended to the alias.
Not for categories.

**Comment by hansdampf-123** [comment]
Just for my understanding: will the image-alias be different than before? e.g. the ID will not be included anymore? That would mean all the indexed pictures on google and co. are to be re-indexed?

**Comment by Elfangor93** [comment]
Yes, the alias will be different. We removed the id in the alias DB field to be consistent with the Joomla core. This makes our life for coding much easier.

But this does not have anything to do with your Google index.
For Google all that matters is the URL created by the Router rather than the alias itself. The plan is to add the ID in the routing such that the URLs will look the same again as for JG3 (with the ID after the alias).

The Routing will be done/optimized for alpha4.

**Comment by hansdampf-123** [comment]
But it does not seem to be possible to change the title (alpha3) , so to remove the "(2)". The Title is automatically changed back. But as in joomla articles it should be possible to have the same title multiple times as long as the alias is different.
If somebody has a category with cats, it should be possible, to name all the pictures "cat", no?

**Comment by hansdampf-123** [comment]
I think this problem was solved with #280? 
With the newest Code form Github, the issue seems to be solved.
