### ISSUE TITLE
syntax error, unexpected end of file, expecting ";" 

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#233]
Status 07.06.2024
No matter what function I address.
Egal, welche Funktion ich anspreche.

![Screenshot 2024-06-07 120015](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/524aaac5-c5ad-4673-ab82-485fd08af85d)

![Screenshot 2024-06-07 120712](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/0ca4ed88-f3c3-4672-b964-6a6a6e75071f)

**Comment by AlexanderSupp** [comment]
The entire frontend shows this error. The error only disappeared after uninstalling JoomGallery.
Komplettes Frontend zeigt diesen Fehler. Erst nach Deinstallation der JoomGallery ist der Fehler verschwunden.

**Comment by MrMusic** [comment]
Füge am Ende der Zeile 67 der Datei administrator/components/com_joomgallery/services/provider.php einen Strichpunkt hinzu:
` };`

**Comment by AlexanderSupp** [comment]
Thanks for your quick response. Now it works.
Small cause with great effect.

**Comment by eumel1602** [comment]
das sollte beim main brunch aber doch nicht passieren oder was verstehe ich da nicht ?

**Comment by AlexanderSupp** [comment]
brunch:
(gegen Mittag eingenommene) ausgedehnte und reichhaltige Mahlzeit, die aus Bestandteilen des Frühstücks und des Mittagessens besteht
branch = zweig
Ihr macht mich noch ganz dusselig. Nehmt Rücksicht auf ältere Leute.

**Comment by eumel1602** [comment]
sorry "T9" am Handy. so , muss jetzt mein mitternachts branch einnehmen
