### ISSUE TITLE
Das Speichern von Benutzern führt zu einem Fehler - Call to undefined method ......

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#234]
![Screenshot 2024-06-07 173759](https://github.com/JoomGalleryfriends/JG4-dev/assets/110494397/ab427e3e-0d38-455d-849c-5c4e99b5490f)

**Comment by AlexanderSupp** [comment]
The error disappeared after uninstalling JoomGallery.

**Comment by eumel1602** [comment]
Fehler kann ich bestätigen. **allerdings nur in J 5.1.1...** (in J 4.4.5 funktioniert es) 
MYSQL Datenbankversion 8.0.26-16  || PHP 8.2.5 || WIN

CS:

![bildschirmabgriff](https://github.com/JoomGalleryfriends/JG4-dev/assets/96334985/5ee2d33a-5e66-4697-8aa9-4041078be1ad)

**Comment by Elfangor93** [comment]
Looks like the system plugin "joomgallery" is not deinstalled when deinstalling JoomGallery.

**Comment by eumel1602** [comment]
Ich installiere den MAIN, Teste das mit dem Benurtzer speichern -> Fehler -> JG4dev deinstallieren -> es ist alles weg auch das system plugin -> Benutzerwerwaltung funktioniert wie erwatet...
