### ISSUE TITLE
Bearbeiten/Loeschen einer Kategorie nach alias Änderung funktioniert nicht

### ISSUE THREAD

**Issue by eumel1602** [JoomGalleryfriends/JG4-dev#236]
J 4.4.5 und auch J5.1.1
Ich erstelle eine Kategorie, vergebe einen eigenen alias, wenig später ändere ich den alias von hand und speichere das ab. 
Nun möchte ich diese Kategorie über das Kategorie hauptmenü löschen, das funktioniert nicht, weil der ursprüngliche alias nicht gefunden wird...  

Fehlermeldung: "Folder not existing. (2)" (die "2" in klammern steht für den originalen alias) 
kann das jemand bestätigen? 
------

![bildschirmabgriff](https://github.com/JoomGalleryfriends/JG4-dev/assets/96334985/ac6274ae-1527-4cc0-9256-1542b37c22c7)

**Comment by Elfangor93** [comment]
>wenig später ändere ich den alias von hand und speichere das ab.

Wurde der Ordner der entsprechenden Kategorie nach dem Speichern im filesystem korrekt umbenannt?

**Comment by eumel1602** [comment]
Sorry für die später meldung. 
Im PG filesystem (via FTP) wird bei jeder änderung de salias ein neue rOrdner angelegft. in allen drei hauptordnern (original/thump/
![Screenshot 2024-06-11 164243](https://github.com/JoomGalleryfriends/JG4-dev/assets/96334985/7917276d-4eed-40e2-a8b1-80a56efe274d)
detail)

**Comment by MrMusic** [comment]
Ergänzung meinerseits:
Beim ändern des Alias wird in der DB die 'path'-Angabe nicht aktualisiert.
