### ISSUE TITLE
Delete button is not displayed

### ISSUE THREAD

**Issue by MrMusic** [JoomGalleryfriends/JG4-dev#237]
If the backend user has 'delete' authorisation, the delete button is displayed.
If the user only has the 'delete own' authorisation, the delete button is not displayed.
This applies to both categories and images.

DE:
Wenn der Backend-Benutzer die Berechtigung 'delete' hat wird der Button zum löschen angezeigt.
Wenn der Benutzer nur die Berechtigung 'delete own' hat wird der Button zum löschen nicht angezeigt.
Das Betrifft sowohl Kategorien als auch Bilder.

**Comment by Elfangor93** [comment]
This issue also applies to the create buttons (create and upload).
