### ISSUE TITLE
Configuration Sets lassen sich nicht speichern

### ISSUE THREAD

**Issue by hansdampf-123** [JoomGalleryfriends/JG4-dev#243]
Ein paar Einstellungen lassen sich speichern, andere nicht:
'* es kommt zwar eine positive Speichermeldung, die Einstellung ist jedoch zurück gesetzt

General Settings	
User Settings
- Common Settings
- Uploads*
- Downloads
- Ratings	
- Comments

Frontend Views
- Category View*
- Single Image View*

Alpha3 on Joomla 5.1.0 / Php 8.3

**Comment by hansdampf-123** [comment]
Update:
die Einstellung lassen sich über den Menupunkt ändern, wozu sind dann die Einstellungen in Configuration Sets?

**Comment by MrMusic** [comment]
Die Configurations Sets gelten für alle Kategorien usw. und können im jeweiligen Menüpukt überschrieben werden.
Das soll in Alpha 4 kommen. In der Alpha3 ist dies noch nicht implementiert.
In der Alpha3 funktionieren die meisten/wichtigsten Einstellungen nur für den jeweiligen Menüpunkt.

**Comment by hansdampf-123** [comment]
ok, klar für Category View aber was ist mit Uploads und Singe Image View?

**Comment by MrMusic** [comment]
>ok, klar für Category View aber was ist mit Uploads und Singe Image View?

Dieses überschreiben der Konfiguration durch die Einstellungen im Menüpunkt gilt für alle views und ist so Joomla-Standard.

**Comment by hansdampf-123** [comment]
Ok, schaue es mir dann beim Alpha4 an. Macht es jedoch Sinn, Einstellungen zu haben welche gar nicht gespeichert werden?

**Comment by MrMusic** [comment]
Die Einstellungen sollten natürlich alle gespeichert werden.
Wenn das nicht der Fall ist, ist entweder etwas noch nicht implementiert oder schlicht ein Bug.
Die "Frontend views" sind aktuell noch nicht fertig, daran wird gerade gearbeitet. Wo genau werden sonst irgendwelche Einstellungen nicht abgespeichert?

**Comment by hansdampf-123** [comment]
Nicht speichern lassen sich die mit *:
General Settings
  User Settings
    Uploads*

Frontend Views
  Category View*
  Single Image View*
  
Ich muss dazu sagen, dass ich die Alpha 2 nicht deinstalliert habe, sonder die Alpha 3 einfach über Joomla drüber installiert habe, falls es dazu zum bug gekommen ist.

**Comment by MrMusic** [comment]
>Ich muss dazu sagen, dass ich die Alpha 2 nicht deinstalliert habe, sonder die Alpha 3 einfach über Joomla drüber installiert habe, falls es dadurch zum bug gekommen ist.

Genau das ist das Problem!
Es muss zwingend die vorherige Alpha-Version deinstalliert werden. Ansonsten gibt es solche "Effekte".

**Comment by hansdampf-123** [comment]
Mit der frischen Installation von Alpha 3 klappt es nun, ausser:

User Settings - Uploads - Frontend upload 
kann nicht deaktiviert werden. die Restlichen Einstellungen in diesem Reiter werden bei speichern übenrommen. Der Frontend upload bleibt jedoch immer aktiv.

**Comment by Elfangor93** [comment]
Wenn eine Einstellung nach dem Speichern nicht erhalten bleibt, dann liegt das daran, dass die entsprechende Kolonne in der DB-Tabelle `#__joomgallery_configs` fehlt.
Das kommt daher, dass die Datenbank nicht dem Stand der aktuellen Version entspricht, oder dass die Kolonne einfach vergessen wurde in der Entwicklung.

**Comment by MrMusic** [comment]
>User Settings - Uploads - Frontend upload
kann nicht deaktiviert werden.

Ja, hier fehlt ein Eintrag in der Datenbank.
Ich habe hier einen Pull Request dafür erstellt: https://github.com/JoomGalleryfriends/JG4-dev/pull/251
Danke für das melden.

**Comment by MrMusic** [comment]
Fixed with https://github.com/JoomGalleryfriends/JG4-dev/pull/251
