### ISSUE TITLE
Wasserzeichen über Orginalbilder

### ISSUE THREAD

**Issue by hansdampf-123** [JoomGalleryfriends/JG4-dev#244]
Ich denke eine Warnung bei den Einstellungen zu den Wasserzeichen über Originalbilder wäre sinnvoll. Wir das Wasserzeichen generiert, ist es fix im Original drin. Wir nun das Wasserzeichen geändert (z.B. kleiner gemacht), wird das neue über das alte Wasserzeichen gelegt. Das kann nicht mehr rückgängig gemacht werden oder?

**Comment by Elfangor93** [comment]
Alle Einstellungen unter "Image processing (static images)" werden während dem Upload fix auf das Bild im Filesystem angewandt.
Du hast recht, wenn man statische Anpassungen am Originalbild vornimmt, hat das entsprechende Effekte (z.B doppeltes Wasserzeichen, wenn Bilder neu generiert werden). Das liegt daran, dass das Originalbiuld als Ursprungs/Quelldatei verwendet wird für eine neu Generierung.
Rückgängig machen ist sehr schwierig. Einzige Möglichkeit wäre, das Originalbild für jedes Bild einzeln im Bild bearbeiten Formular mit einem Bild zu erstzten, welches noch nicht statisch verändert wurde. Also noch wirklich original ist.

> Ich denke eine Warnung bei den Einstellungen zu den Wasserzeichen über Originalbilder wäre sinnvoll.

Du hast recht, eine Wranung oder Hinweis bei den statischen Bildverarbeitungsoptionen, das Orginial betreffend wäre sinnvoll. Hast du einen konkreten Vorschlag?

**Comment by hansdampf-123** [comment]
> Hast du einen konkreten Vorschlag?

Würde unter Configuration Sets - General Settings - Image Processing bei den Settings für das Original (dort wiederum unterster Punkt) die Warnung anbringen:
"Wasserzeichen werden permanent in das Originalbild eingefügt, eine Änderung ist nicht möglich. Dies hat auch Auswirkungen auf die anderen Bildformate."

Wenn jemand unachtsam die Einstellung ändert oder ausprobiert und dabei die Bilder neu generiert, kann das auch die Bilder futsch machen. Wäre es eine Option, neben dem Original noch ein unveränderbares Original zu haben welches gar nicht veröffentlicht ist? So wären die Bilder quasi gesichert.
Ich kann mir vorstellen, dass viele die Galerie auch als Speicherort sehen und die Origianlbilder auf dem Rechner nach dem Hochladen löschen.

**Comment by hansdampf-123** [comment]
Ich habe gerade gesehen, dass wir das unter #142 schon mal besprochen haben. Ist also leider doppelt und mindestens eines kann weg.

**Comment by Elfangor93** [comment]
Mot PR #246 wird es einen Hinweistext in den Einstellungen drin haben.
