### ISSUE TITLE
Migrationsfehler

### ISSUE THREAD

**Issue by hansdampf-123** [JoomGalleryfriends/JG4-dev#249]
Sorry für meine vielen Beiträgt, ich hoffe es ist ok einfach alles melden was nicht klappt.

Hatte alles auf dem neusten Stand und wollte die Migration nochmals testen. Alle Joomgallery Komponenten gelöscht und neu installiert. Nun kommt bei der Migration schon vor dem 1. Schritt diese Meldung:
Joomgallery\Component\Joomgallery\Administrator\Model\MigrationModel::getParams(): Return value must be of type array, Joomla\Registry\Registry returned
<img width="1384" alt="Bildschirmfoto 2024-06-20 um 20 59 05" src="https://github.com/JoomGalleryfriends/JG4-dev/assets/143128286/0b019086-8bcf-433b-90f1-a73036478944">

Joomgallery Alpha 3, Joomla 5.1, PHP 8.3

**Comment by eumel1602** [comment]
bin mir nicht sicher ob dieses php 8.3 da auch ne rolle spielt?!... klar melden ist immer gut...

**Comment by hansdampf-123** [comment]
> bin mir nicht sicher ob dieses php 8.3 da auch ne rolle spielt?!... 

Habe es mit PHP 8.2 gerade versucht – gleiches Resultat.
Ich habe davor die Alpha 2 deinistaliert, Alpha 3 installiert und erfolgreich von Joomla 3 migriert. Nach erneutem Löschen der Alpha 3 ging es nun nicht mehr.

**Comment by hansdampf-123** [comment]
Hab das Alpha3 ohne deinstallation der Fehlerhaften Alpha3 nochmals installiert, nun klappt es...

**Comment by hansdampf-123** [comment]
Fehler konnte nicht rekonstruiert werden, schliesse den issue
