### ISSUE TITLE
Categories have different IDs after migration

### ISSUE THREAD

**Issue by LimeArts** [JoomGalleryfriends/JG4-dev#255]
"After migrating an installation with several hundred categories, I noticed that the newly created categories in Alpha 3 have a different ID than in the live environment.

Since the installation makes extensive use of the joomplucat shortcuts, this would cause quite a bit of chaos in a release version."
![grafik](https://github.com/user-attachments/assets/33711941-0e45-45cb-96dd-71e342fdd13f)
![grafik](https://github.com/user-attachments/assets/0845d3c4-50ff-49ce-b921-a04462f4ef32)

**Comment by Elfangor93** [comment]
It depense what you have configured in the migration settings.

You can choose there to migrate using the same IDs. But this is only possible if you migrate into an empty JoomGallery 4 installation.

**Comment by Elfangor93** [comment]
@LimeArts Do the ` migration settings` solve your problem? Can I close this issue?
