### ISSUE TITLE
Frontend - Display of a random image if no category image is set

### ISSUE THREAD

**Issue by reilldesign** [JoomGalleryfriends/JG4-dev#260]
The following setting in the configuration set is not yet effective – Display of a random image if no category image is set.

For the upcoming beta version it would be great if this function was already implemented.

**Comment by MrMusic** [comment]
Yes, I'm in favour of that too.

**Comment by rowi68** [comment]
I would also like to support this wish...

**Comment by AlexanderSupp** [comment]
> Display of a random image if no category image is set.

It would be great if the function "random images" can be combined with "categories" and a third field for "Search Child Categories=Yes/No".

**Comment by Elfangor93** [comment]
> It would be great if the function "random images" can be combined with "categories" and a third field for "Search Child Categories=Yes/No".

@AlexanderSupp Was meinst du damit? Dass auch Unterkategorien berücksichtigt werden, wenn ein zufälliges Bild ausgewählt wird?

**Comment by AlexanderSupp** [comment]
@Elfangor93 
Richtig erkannt.
