### ISSUE TITLE
[IMGtools Service]: Black bar when watermarking and cropping

### ISSUE THREAD

**Issue by Elfangor93** [JoomGalleryfriends/JG4-dev#262]
If 'cropping' is set for the image resizing and a watermark is to be inserted, the watermark is inserted with a shift and a black bar also appears.
This applies to both 'dynamic' and 'fixed' image processing.
Image processor: GD

![344583641-8dc60a01-0cb4-4d0a-ae17-5b0453d1d7ae](https://github.com/user-attachments/assets/31ddb761-63e2-4c8a-8031-f45a0356fafa)

**Comment by MrMusic** [comment]
Fixed with PR #289
