### ISSUE TITLE
Recording Date has date of upload

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#266]
Test with main status from  2.10.2024
The recording date is not the date of EXIF-Value.
All recording dates have date of upload day.
Can anybody confirm this?

**Comment by eumel1602** [comment]
meinst du das hier? 
![1](https://github.com/user-attachments/assets/6143c5ef-e6ec-4e92-a3f0-61994cb98f8d)
(winterbild am 2.10. kann ja nicht sein)

**Comment by MrMusic** [comment]
Bei mir funktioniert die Übernahme der Metadaten problemlos.
Was hast du in der Konfiguration eingestellt für das Quell- und Zielfeld?
![Upload-use-metadata](https://github.com/user-attachments/assets/d984c016-202f-4638-8d0c-722116f9558b)

**Comment by eumel1602** [comment]
stimmt, das muss eingestellt werden. hatte ich vergessen. Es funktioniert also auch bei mir ! 
da kann alexander evt. bestätigen und wir können den fehler wieder zu machen...

**Comment by AlexanderSupp** [comment]
Danke euch beiden für die schnelle Reaktion.
Das hatte ich total vergessen, dass bei der JG in den Einstellungen diese Funktion extra gesetzt werden muss.
(Das ist sonst bei keiner mir bekannten anderer Software erforderlich)
Vielleicht gibt es einen Sinn, die vorstehende Einstellung (von @MrMusic) für Recording Date als Standard in der Configuration für die Installation so aufzunehmen (analog den Settings zu Imagetype).
Es ist schon ziemlich blöd, wenn man nach der umfangreichen Migration oder dem Hochladen vieler Bilder das Fehlen des Aufnahmedatums feststellt.
Gerne würde ich dieses Issue noch offen halten, bis hier eine Lösung im Rahmen der EXIF-Überarbeitung gefunden wurde.

**Comment by eumel1602** [comment]
ohne technich zu wissen was ich erzähle, würde ich das bestätigen. lieber gleich die rohdaten übernehmen als es unbedingt vorher einstellen zu müssen...

**Comment by AlexanderSupp** [comment]
Das Thema wurde mit PR  "Change default config settings #269" erledigt, weshalb ich dieses Issue schließe.
The issue has been resolved with PR "Change default config settings #269", so I am closing this issue.
