### ISSUE TITLE
[lang] language files are not installed

### ISSUE THREAD

**Issue by ThomasFinnern** [JoomGalleryfriends/JG4-dev#27]
The xml file refers to some language files but the are not installed

The layout recommended in astridX boilerplate is to just include the folders as reference 
Same for admin or site or plugin or module

`		<files folder="administrator/components/com_foos">
			<filename>access.xml</filename>
                           ....
			<folder>language</folder>
                           ....
			<folder>tmpl</folder>
		</files>
`

**Comment by Elfangor93** [comment]
This was addressed in #34.
