### ISSUE TITLE
Package with plugins and module folder

### ISSUE THREAD

**Issue by ThomasFinnern** [JoomGalleryfriends/JG4-dev#28]
Just for info (to be checked)

it may be feasible to add all plugins and modules into the component xml file

Still in boilerplate two paths are used additionally for packages

...\administrator\packages\pkg_foos.xml
...\administrator\packages\pkg_foos.xml

Also a separate intall script is there each
Sorry i don't know it more specific

**Comment by szepty-ziemi** [comment]
@Elfangor93 Is this ticket solved or needs to be tested somehow?

**Comment by Elfangor93** [comment]
This needs to be discussed whether we want to create a package or not
