### ISSUE TITLE
[lang] uses: folder language(s) <-> language

### ISSUE THREAD

**Issue by ThomasFinnern** [JoomGalleryfriends/JG4-dev#29]
Should we use folder language**s** or language
Actually language**s** is used. 

In 3.x => Developing an MVC Component/Adding language management
https://docs.joomla.org/J3.x:Developing_an_MVC_Component/Adding_language_management

The folder looks like 
* site/language/en-GB/en-GB.com_helloworld.ini
* admin/language/en-GB/en-GB.com_helloworld.ini

In backend not components look like using the singular form (mostly)
So i recommend to change this accordingly

**Comment by Elfangor93** [comment]
This was addressed in #34 .
