### ISSUE TITLE
Add "_old" at each installation

### ISSUE THREAD

**Issue by hansdampf-123** [JoomGalleryfriends/JG4-dev#291]
Mit der neusten Version der JG4-dev (inkl PR 288) kann bei mir JoomGallery nicht mehr installiert werden.
Es kommt folgende Meldung:
<img width="1101" alt="Bildschirmfoto 2024-12-02 um 09 33 58" src="https://github.com/user-attachments/assets/5c7431db-c62a-4ddc-abde-ac6aad07295d">

Wird der Tabellenname evtl. zu lange, wenn bei jeder neuinstallation "_old" angefügt wird?

Wenn die Tabellen gelöscht werden klappt es mit der Neuinstallation. Ist wahrscheinlich ein Problem das nur beim Testen vorkommt?

**Comment by Elfangor93** [comment]
Each time JG4 is installed it adds a "_old" at the end of existing JG3 tables. This results in various. To solve the problem the db tables have to be renamed manually.
