### ISSUE TITLE
Migration Manager error

### ISSUE THREAD

**Issue by hansdampf-123** [JoomGalleryfriends/JG4-dev#298]
Migration fails at Step 3, Migration: Categories with the Error :
[Success] [Migrator.js] Migration of category with id = 1 successful.
[Info] Error in server response. We will try again. (1/3)
**[Fehler] Call to undefined method Joomla\Event\Event::getItem()**

<img width="1399" alt="Bildschirmfoto 2024-12-09 um 16 24 43" src="https://github.com/user-attachments/assets/29491a36-4aa0-4a90-aa2e-f16feb29b335">

source:
Joomgallery 3.6.2
Joomla 3.10.12

destination:
Joomgallery 4.0.0 dev
Joomla 5.2.2

I've done this kind of migration on a other side with out any problems, but here something is not working. Any idea?

**Comment by Elfangor93** [comment]
This error was probably introduced with PR #292. Can you provide me with a full call stack of the error?
You can get that when looking into the network tab of your browser console...

**Comment by MrMusic** [comment]
>[Fehler] Call to undefined method Joomla\Event\Event::getItem()

Den Fehler kann ich bestätigen:
```
[Error] Call to undefined method Joomla\Event\Event::getItem()

[Error] 
#0 C:\xampp81_12\htdocs\j5-test\libraries\vendor\joomla\event\src\Dispatcher.php(454): Joomgallery\Plugin\System\Joomowner\Extension\JoomgalleryOwner->onMigrationBeforeSave(Object(Joomla\Event\Event)) 
#1 C:\xampp81_12\htdocs\j5-test\administrator\components\com_joomgallery\src\Model\MigrationModel.php(1290): Joomla\Event\Dispatcher->dispatch('onMigrationBefo...', Object(Joomla\Event\Event)) 
#2 C:\xampp81_12\htdocs\j5-test\administrator\components\com_joomgallery\src\Model\MigrationModel.php(807): Joomgallery\Component\Joomgallery\Administrator\Model\MigrationModel->insertRecord('category', Array, false) 
#3 C:\xampp81_12\htdocs\j5-test\administrator\components\com_joomgallery\src\Controller\MigrationController.php(809): Joomgallery\Component\Joomgallery\Administrator\Model\MigrationModel->migrate('category', 28)
```

**Comment by hansdampf-123** [comment]
After upgrade (including #283) at the same step. These Errors show up:
(Joomla 5.2.2., Joomgallery deleted and newly installed)

[Success] [Migrator.js] Migration of category with id = 1 successful.

[Info] Error in server response. We will try again. (1/3)

[Fehler] Call to undefined method Joomla\Event\Event::getItem()

[Fehler] #0 /home/kostumka/www/sammlung4/libraries/vendor/joomla/event/src/Dispatcher.php(454): Joomgallery\Plugin\System\Joomowner\Extension\JoomgalleryOwner->onMigrationBeforeSave(Object(Joomla\Event\Event)) #1 /home/kostumka/www/sammlung4/administrator/components/com_joomgallery/src/Model/MigrationModel.php(1367): Joomla\Event\Dispatcher->dispatch('onMigrationBefo...', Object(Joomla\Event\Event)) #2 /home/kostumka/www/sammlung4/administrator/components/com_joomgallery/src/Model/MigrationModel.php(877): Joomgallery\Component\Joomgallery\Administrator\Model\MigrationModel->insertRecord('category', Array, false) #3 /home/kostumka/www/sammlung4/administrator/components/com_joomgallery/src/Controller/MigrationController.php(813): Joomgallery\Component\Joomgallery\Administrator\Model\MigrationModel->migrate('category', '53') #4 /home/kostumka/www/sammlung4/libraries/src/MVC/Controller/BaseController.php(730): Joomgallery\Component\Joomgallery\Administrator\Controller\MigrationController->start() #5 /home/kostumka/www/sammlung4/libraries/src/Dispatcher/ComponentDispatcher.php(143): Joomla\CMS\MVC\Controller\BaseController->execute('start') #6 /home/kostumka/www/sammlung4/administrator/components/com_joomgallery/src/Dispatcher/Dispatcher.php(32): Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() #7 /home/kostumka/www/sammlung4/libraries/src/Component/ComponentHelper.php(361): Joomgallery\Component\Joomgallery\Administrator\Dispatcher\Dispatcher->dispatch() #8 /home/kostumka/www/sammlung4/libraries/src/Application/AdministratorApplication.php(150): Joomla\CMS\Component\ComponentHelper::renderComponent('com_joomgallery') #9 /home/kostumka/www/sammlung4/libraries/src/Application/AdministratorApplication.php(195): Joomla\CMS\Application\AdministratorApplication->dispatch() #10 /home/kostumka/www/sammlung4/libraries/src/Application/CMSApplication.php(306): Joomla\CMS\Application\AdministratorApplication->doExecute() #11 /home/kostumka/www/sammlung4/administrator/includes/app.php(58): Joomla\CMS\Application\CMSApplication->execute() #12 /home/kostumka/www/sammlung4/administrator/index.php(32): require_once('/home/kostumka/...') #13 {main}
