### ISSUE TITLE
falsche URLs in der en_GB file com_joomgallery.ini 

### ISSUE THREAD

**Issue by eumel1602** [JoomGalleryfriends/JG4-dev#302]
In der **Sprachen** **Originaldatei:** en_GB file com_joomgallery.ini sind jetzt bald falsche URLs drin. 
Mit der "Inbetriebnahme" der neuen JG Webseite werden wohl die URLS: "https://www.en.joomgalleryfriends.net/" nicht mehr funktionieren.
aktuell 4 strings betroffen...
aus meiner Sicht sind andere Übersetzungsdatein nicht betroffen.

**Comment by Elfangor93** [comment]
This will be fixed with PR #305
