### ISSUE TITLE
PHP Error with Code mirror

### ISSUE THREAD

**Issue by hansdampf-123** [JoomGalleryfriends/JG4-dev#304]
With the newest main I got the following issues:
The category migration in Step 3 went trough. Image migration stuck after some time. After a restart, the images all went through.
The backend control panel looks good, but under images and categories this error is shown many times:
Warning: Attempt to read property "owner" on bool in /home/kostumka/www/sammlung4/administrator/components/com_joomgallery/src/Service/Access/Base/AccessOwn.php on line 144
When I click on a image in the backend (under images) i get this error
3 arguments are required, 2 given
Call Stack
# | Function | Location
1 | () | JROOT/libraries/src/Language/Text.php:281
2 | sprintf() | JROOT/libraries/src/Language/Text.php:281
3 | Joomla\CMS\Language\Text::sprintf() | JROOT/plugins/editors/codemirror/layouts/editors/codemirror/codemirror.php:64
4 | include() | JROOT/libraries/src/Layout/FileLayout.php:128
5 | Joomla\CMS\Layout\FileLayout->render() | JROOT/libraries/src/Layout/LayoutHelper.php:76
6 | Joomla\CMS\Layout\LayoutHelper::render() | JROOT/plugins/editors/codemirror/src/Provider/CodeMirrorProvider.php:164
7 | Joomla\Plugin\Editors\CodeMirror\Provider\CodeMirrorProvider->display() | JROOT/libraries/src/Editor/Editor.php:211
8 | Joomla\CMS\Editor\Editor->display() | JROOT/libraries/src/Form/Field/EditorField.php:251
9 | Joomla\CMS\Form\Field\EditorField->getInput() | JROOT/libraries/src/Form/FormField.php:482
10 | Joomla\CMS\Form\FormField->__get() | JROOT/libraries/src/Form/Field/TextareaField.php:94
11 | Joomla\CMS\Form\Field\TextareaField->__get() | JROOT/libraries/src/Form/Field/EditorField.php:138
12 | Joomla\CMS\Form\Field\EditorField->__get() | JROOT/libraries/src/Form/Form.php:458
13 | Joomla\CMS\Form\Form->getInput() | JROOT/administrator/components/com_joomgallery/tmpl/image/edit.php:65
14 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:416
15 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:204
16 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_joomgallery/src/View/Image/HtmlView.php:102
17 | Joomgallery\Component\Joomgallery\Administrator\View\Image\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:697
18 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_joomgallery/src/Controller/DisplayController.php:119
19 | Joomgallery\Component\Joomgallery\Administrator\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
20 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
21 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/administrator/components/com_joomgallery/src/Dispatcher/Dispatcher.php:32
22 | Joomgallery\Component\Joomgallery\Administrator\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
23 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
24 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
25 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
26 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
27 | require_once() | JROOT/administrator/index.php:32

the frontend shows this:
Call Stack
# | Function | Location
1 | () | JROOT/libraries/src/Router/Router.php:155
2 | Joomla\CMS\Router\Router->parse() | JROOT/libraries/src/Application/SiteApplication.php:754
3 | Joomla\CMS\Application\SiteApplication->route() | JROOT/libraries/src/Application/SiteApplication.php:244
4 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
5 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:58
6 | require_once() | JROOT/index.php:32

**Comment by Elfangor93** [comment]
Can you check, if the user id exists which got assigned to the images or categories during migration?

Look for the row created_by in the table #__joomgallery and check if the id in there exists ib the table #__users.

**Comment by hansdampf-123** [comment]
Yes, the user "984" as listed in created_by in #__joomgallery is existing in #__users. There was no change in the users since the migration of the destination site from joomla 3 to 5.

**Comment by Elfangor93** [comment]
Does anyone can confirm this issue?
Is it reproducible?

It seems as if code mirror editor is throwing the error...

**Comment by hansdampf-123** [comment]
With code mirror switched off I can access Images :: Edit Image, but the other errors are still there:
Warning: Attempt to read property "owner" on bool in /home/kostumka/www/sammlung4/administrator/components/com_joomgallery/src/Service/Access/Base/AccessOwn.php on line 144

and the frontend ones.

**Comment by MrMusic** [comment]
>Warning: Attempt to read property "owner" on bool in /home/kostumka/www/sammlung4/administrator/components/com_joomgallery/src/Service/Access/Base/AccessOwn.php on line 144

PHP warning confirmed. Joomla 5.2.2, PHP 8.1

>When I click on a image in the backend (under images) i get this error
3 arguments are required, 2 given

I can't confirm this. 
@hansdampf-123 Can you test with backend language en-GB?

**Comment by hansdampf-123** [comment]
> > When I click on a image in the backend (under images) i get this error
> > 3 arguments are required, 2 given
> 
> I can't confirm this. @hansdampf-123 Can you test with backend language en-GB?

This was solved by switching code mirror off. The other issues (backend and frontend) are the same with de-DE and en-GB as backend language. With the exception of the alias description in en-GB being much shorter.

**Comment by MrMusic** [comment]
>This was solved by switching code mirror off

Can you use with codemirror and en-GB? Error gone?

**Comment by hansdampf-123** [comment]
> Can you use with codemirror and en-GB? Error gone?
thank you for making that clear, and yes I can confirm, the error is gone with codemirror on and backend-language en-GB (but error with de-DE)

**Comment by Elfangor93** [comment]
> Warning: Attempt to read property "owner" on bool in /home/kostumka/www/sammlung4/administrator/components/com_joomgallery/src/Service/Access/Base/AccessOwn.php on line 144

Please add a separate issue for that.

**Comment by MrMusic** [comment]
Es scheint sich hier um einen Joomla Bug zu handeln, der dann Auftritt wenn eine Seite von Joomla 3 auf Joomla 4 migriert wird und Codemirror zusammen mit dem alten de-DE Sprachpaket verwendet wird.
Siehe z.B.: https://forum.joomla.de/thread/18512-templates-anpassen-neue-datei/?postID=131626#post131626
@hansdampf-123 Ist bei dir nach der Migration noch das alte de-DE Sprachpaket von Joomla 3 installiert?
Ist der Fehler beseitigt wenn du vor Start der JoomGallery-Migration das neue Joomla 4 de-DE Sprachpaket installierst und aktivierst?

**Comment by hansdampf-123** [comment]
@MrMusic Volltreffer – Danke.
Neuste Sprachdatei installiert. Joomgallery neu installiert und migriert. Problem mit Code Mirror gelöst.
Vielleicht reicht es hier, diesen Lösungsansatz einfach in die Dokumentation aufzunehmen?

**Comment by hansdampf-123** [comment]
Diese issue kann geschlossen werden, da es ein Bug von code mirror resp. den Sprachdateien ist und nicht der JoomGallery.
