### ISSUE TITLE
Unused setting "Ordering numbers"

### ISSUE THREAD

**Issue by Elfangor93** [JoomGalleryfriends/JG4-dev#307]
Currently there is an unsused setting with label `Ordering numbers` in the config manager which was also available in JG3. This would affect the ordering of images when uploaded with a multiple upload method.

![grafik](https://github.com/user-attachments/assets/a934662c-ed8c-4829-b900-86d5b8ca1738)

Do you think we still need this setting?
If yes does it needs to be available in the first version?

@MrMusic Whats your impression about that?

**Comment by MrMusic** [comment]
I don't think we need this function in the first version.
If someone urgently needs this function, they will get in touch.

**Comment by Elfangor93** [comment]
If we decide to add it, this would be the PR for it #308

**Comment by Elfangor93** [comment]
Fixed with PR #308
