### ISSUE TITLE
Save image without file name 

### ISSUE THREAD

**Issue by rowi68** [JoomGalleryfriends/JG4-dev#314]
When saving the image by right-clicking, the file name is not displayed but only  "index.jpg".

**Comment by Elfangor93** [comment]
Plase provide more details on how to reproduce this issue. Which steps have you done to create this issue?

**Comment by rowi68** [comment]
I did right-click with mouse on an image 
![2024-12-29_14h30_41](https://github.com/user-attachments/assets/9c8775dc-d6b0-4457-81e6-3ec377933f40)

and when I want to save the name of image is always "index"

![2024-12-29_14h48_53](https://github.com/user-attachments/assets/6efaddef-f8b2-4b57-88e7-2a48ef84ea2c)

**Comment by Elfangor93** [comment]
> I did right-click with mouse on an image

Where exactly? In detail view? In lightgallery?
Whats the image alias and the filename of the image you try to store?

**Comment by rowi68** [comment]
Yes, it is in detail view. But in lightbox is same result.

The image alias is in this case is "testbild1" and title of image  "Testbild1"

Browser Console displays:
![2024-12-29_15h56_00](https://github.com/user-attachments/assets/a9c241f9-5986-44ad-9491-1146e82a96c5)

**Comment by rowi68** [comment]
@Elfangor93 
I installed JG4 new and now saving with filename is o.K. 
I don´t know what was the reason before.
So I close this issue....
