### ISSUE TITLE
[Uploader Service]: Gif images are not processed with IM

### ISSUE THREAD

**Issue by Elfangor93** [JoomGalleryfriends/JG4-dev#32]
Error when uploading GIF image and process it with ImageMagick.
ImageMagick does not list GIF as a supported image type (command: magick -version).

Error happens in HTMLUploader.php line 98.

**Comment by Elfangor93** [comment]
Issue will be resolved with PR #31 ...

**Comment by szepty-ziemi** [comment]
I have an error while trying to upload gif nad IM as an image processor:

![obraz](https://user-images.githubusercontent.com/60470150/188197432-83bc9971-45f7-4066-85c1-a95091f01cc3.png)

**Comment by Elfangor93** [comment]
Error solved in PR https://github.com/JoomGalleryfriends/JG4-dev/pull/31

**Comment by szepty-ziemi** [comment]
Okay, now we get "Invalid Image Type" notification:

![obraz](https://user-images.githubusercontent.com/60470150/188237475-38a9f79f-7b6d-4a36-a342-c16525303969.png)

**Comment by szepty-ziemi** [comment]
Can't be retested due to error in Configuration Manager:

![obraz](https://user-images.githubusercontent.com/60470150/194593828-0e2c41f0-cd3b-47a7-bfd7-bcf8c0890337.png)
