### ISSUE TITLE
[IMGtools service]: Wrong error message when processor not available

### ISSUE THREAD

**Issue by Elfangor93** [JoomGalleryfriends/JG4-dev#36]
### Steps to reproduce:
- Selecting an image processor which is not available on the system.
- Creating a new image

### Result:
Error message:
![grafik](https://user-images.githubusercontent.com/39154009/188485109-9fcd462a-1f28-4f1a-a883-58764f2684b4.png)

### System:
![grafik](https://user-images.githubusercontent.com/39154009/188485239-bc900634-7b04-4963-8bef-fb7b6b4acca7.png)

**Comment by AlexanderSupp** [comment]
In JoomGallery 3.6.0 the ImageMagick Module works correct and is available.
In JoomGallery 4.0 Test the message "Invalid Image Type" will be displayed.
Both systems work with PHP 8.1 in an identical environment of DomainFactory.

![Screenshot 2022-09-08 172424](https://user-images.githubusercontent.com/110494397/189176955-b7a1620f-44e5-49ef-9f14-c686f1fbc8c5.png)
![Screenshot 2022-09-08 172946](https://user-images.githubusercontent.com/110494397/189176990-3a4a9767-b69f-4ddd-ba22-db3fcf1af2d0.png)
![Screenshot 2022-09-08 173541](https://user-images.githubusercontent.com/110494397/189177028-8bcde017-d22f-4903-afd9-af85b1b57371.png)

**Comment by AlexanderSupp** [comment]
The title of this issue
"Wrong error message when processor not available"
 is not correct.
ImageMagick is available, as the screenshot below shows.
But the displayed version is the library version of ImageMagick not the compiled module.
All data in the screenshots after.
There is a bug within the image process ImageMagick.
It seems that image processing with GD Library works correctly.
But there is an error message that "GD Library not found".
All tests were done with the same photo object.
![ImapeProcess-Image-Magick-LibraryCorrect-Screenshot 2022-11-11 114102](https://user-images.githubusercontent.com/110494397/201329152-6be2d99c-ffa3-4cb3-a4a6-df653413c97d.jpg)
![ImageProcess-Image-Magick-Screenshot 2022-11-11 113311](https://user-images.githubusercontent.com/110494397/201329206-17ccbf83-c92c-4f4d-81b4-32c09db57a72.jpg)
![EditImage-Before-Save-Screenshot 2022-11-11 114956](https://user-images.githubusercontent.com/110494397/201329632-2dbe7eac-6f5f-4dff-9265-393968b80a44.jpg)
![EditImage-After-Save-Screenshot 2022-11-11 115152](https://user-images.githubusercontent.com/110494397/201329656-39d45f0a-6c5d-4aac-8adf-f8c0ed6d3613.jpg)
![EditImage-After-Save-Screenshot 2022-11-11 115758](https://user-images.githubusercontent.com/110494397/201330660-707fe57b-efed-4eda-9a5d-a521268d512f.jpg)
![ImageProcess-GD-Lib-Screenshot 2022-11-11 113102](https://user-images.githubusercontent.com/110494397/201330778-ac30da1d-afe2-4e43-b657-15e374fbc363.jpg)
![ImageProcess-GD-Lib-Correct-Screenshot 2022-11-11 114252](https://user-images.githubusercontent.com/110494397/201330849-4ac2633e-030d-4511-a22b-e90d35e4cd0b.jpg)

**Comment by AlexanderSupp** [comment]
Take a look at issue #62 it's from my point of view, the same problem.
