### ISSUE TITLE
[ConfigManager] Path too long when changing watermark file in configuration

### ISSUE THREAD

**Issue by MrMusic** [JoomGalleryfriends/JG4-dev#40]
## Steps to reproduce the issue

- Select a new image in Configuration Manager >> General Settings >> Image Processing >> Watermark
- Klick save

## Expected result

The configuration should be saved without error

## Actual result

Error Message:
**Save failed with the following error: Data too long for column 'jg_wmfile' at row 1** 

## System information

Joomla 4.2.2
JoomGallery 4 actual main branch
PHP 8.1

The reason is the new long image path when using the Joomla Media Manager. More info: [https://ghsvs.de/programmierer-schnipsel/joomla/319-joomla-4-einleitungs-beitragsbild-komische-pfade](https://ghsvs.de/programmierer-schnipsel/joomla/319-joomla-4-einleitungs-beitragsbild-komische-pfade)

Either only the pure path without additions must be stored in the database or the length of the database field must be increased (to 255 Chars?).

**Comment by Elfangor93** [comment]
From my opinion we should get rid of the additions. They are not needed for our usecase...

**Comment by Elfangor93** [comment]
fixed accordingly in PR #47

**Comment by MrMusic** [comment]
Closed as completed.
