### ISSUE TITLE
[FileManager service] Wrong path after moving category

### ISSUE THREAD

**Issue by MrMusic** [JoomGalleryfriends/JG4-dev#44]
## Steps to reproduce the issue

Create two main categories: Cat-A and Cat-B
Create new images in Cat-B
Move Cat-B as subcategory under Cat-A
Check file structure ->Here is all ok
Create new image in Cat-B
Check file structure

## Expected result

The new images should be stored in the folder xxx\cat-a\cat-b
The path entry in the database table should be \cat-a\cat-b

## Actual result

The images are stored in (an automatically created) folder \cat-b.
This directory is not created as a subcategory under Cat-A but as a new main category.
The path entry in the database category table is incorrect: \cat-b instead \cat-a\cat-b

![wrong-path-structure](https://user-images.githubusercontent.com/9802593/194840889-a8611c4c-7381-4010-8277-49518072fcf5.jpg)

## System information

Joomla 4.2.3
JoomGallery 4 actual main branch
PHP 8.1

**Comment by MrMusic** [comment]
Additional hint:
when changing the category title and alias, the folder name (path in #__categories) would also have to be changed in the folder structure, this does not work.

**Comment by Elfangor93** [comment]
Fixed in PR #86 ...
