### ISSUE TITLE
What should happen when changing the storage location of imagetypes?

### ISSUE THREAD

**Issue by Elfangor93** [JoomGalleryfriends/JG4-dev#48]
The storage location of an image in the filesystem is derived based on two settings in the config manager:
- General Settings/Common Settings/Filesystem --> root of the filesystem
- Image Processing/Static images/Root path --> path to imagetype folder

Now if you change one of these settings after you already uploaded some images or created some categories, JoomGallery will create a mess.
- The path to **_images uploaded before the change_** will not be created correcty and the images will not be shown anymore.
- **_New uploaded images_** will be threatened correctly.

As a result, changing one of these settings requires many operations to bring everything back into line especially for large galleries. Changing this settings and start this operations could cause many problems if some of the operations fail for some reason.

How can we tackle this problem?
How can we realize a GUI which leads an administrator correctly through this procedure?
Do you think its even a good idea placing this settings in the config manager?

**Comment by szepty-ziemi** [comment]
We need to take into account that most users are inexperienced admins. They just want it work out-of-the-box. Giving them less options will result with less mess in the system. We can hide this settings behind a select: default - will hide them and sett default paths, advanced - will expand those settings with warning eg. "Be careful with changing this settings as it may result with gallery malfunction" or something similar.

**Comment by Elfangor93** [comment]
Maybe we add a new tab for delicate settings where there is a message telling that you should change settings in this section only if you are nowing what you do.

**Comment by szepty-ziemi** [comment]
That's a good option too, with disclaimer "Don't change anything unless you're know what you're doing" 😄

**Comment by AlexanderSupp** [comment]
The optional mapping of the imagetypes are great. All actions in the background are transparent for experienced administrators.
I would also recommend a warning when using it. It is now possible to store images outside of the images directory. Now I have no duplicate files in the Images directory.

**Comment by Elfangor93** [comment]
Lets continue in the discussion #64
