### ISSUE TITLE
[Frontend] Masonry or mosaic style for JoomlaGallery

### ISSUE THREAD

**Issue by dahauz** [JoomGalleryfriends/JG4-dev#52]
Hello, dear JoomlaGallery developers, I really love JoomGallery, but I don’t understand why JG still does not know how to show horizontal and vertical photos in "masonry" or "mosaic" style like any gallery can do it now? Please devote time to this topic.

And the second, please make possibility to move the photos in the necessary order by mouse.

Thank you.

Examples of styles:

https://gates-fluid-demo.squarespace.com

![This is an image](https://i120.fastpic.org/big/2022/1121/49/08c1226ecb1fab91b22e02336dde7149.jpg)
![This is an image](https://i120.fastpic.org/big/2022/1121/41/2378448d44e70ee71d0b87781437df41.jpg)
![This is an image](https://i120.fastpic.org/big/2022/1121/8f/ce6bc6febc11435fc6806e36840c1e8f.jpg)
![This is an image](https://i120.fastpic.org/big/2022/1121/15/cc43dc90fffef1d86e94a62f91e0e215.jpg)

**Comment by Elfangor93** [comment]
Crossposting:
https://www.forum.joomgalleryfriends.net/forum/index.php?thread/320-how-to-show-horizontal-and-vertical-photos-in-masonry-or-mosaic-style/&postID=1552#post1552

**Comment by Elfangor93** [comment]
@dahauz Is implemented with PR #167. Issue will be closed.
