### ISSUE TITLE
[IMGtools service]: Wrong debug message GD Library not found

### ISSUE THREAD

**Issue by Elfangor93** [JoomGalleryfriends/JG4-dev#61]
Issue detected by @szepty-ziemi 
-----

In my configuration I have GD library: https://prnt.sc/75dTeU2uEsl3
But when set in Global Configuration GD option and try to upload a file:
![grafik](https://user-images.githubusercontent.com/39154009/210221338-5b29a182-234b-4fd2-a8f0-2d0347064abf.png)
It says : GD Library not found. Make sure GD is activated in your PHP settings (php.ini).
But image is uploaded and created correctly.
Also in PHP information it says that WEBP support is enabled in GD. Trying to upload webp ends with:
![grafik](https://user-images.githubusercontent.com/39154009/210221363-fde08fa3-caf0-4de2-871c-0372a0dea48e.png)

**Comment by AlexanderSupp** [comment]
Old wine in new bottles. See #36, Nov 11.
