### ISSUE TITLE
Images - How can I change the owner of an image?

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#65]
As an admin, often I load and prepare images for other users.
How can I change the owner of an image?

**Comment by MrMusic** [comment]
The Owner is the 'Created By' field and can be set in the 'Publishing' tab.
Click on the user icon near to the user name and then select a user.
![image-change-owner](https://user-images.githubusercontent.com/9802593/210414773-3b189b44-5afb-4e68-bf71-6028ca5423fe.jpg)

**Comment by AlexanderSupp** [comment]
It would be nice and consistent if we changed the field name “Created By” to “Owner”.
Thanks in advance.

**Comment by Elfangor93** [comment]
The previous field owner is renamed in JG4 to author
![grafik](https://user-images.githubusercontent.com/39154009/211341442-1f94fc3a-f1ab-4989-9c66-7f937a83b32e.png)

The other field you mentioned is just the user who uploaded the image and created the record in the database
![grafik](https://user-images.githubusercontent.com/39154009/211341657-ab43e2a6-f044-42e3-b076-caae0ea77b25.png)

**Comment by Elfangor93** [comment]
>But why we have different names in the two screens for the same field?

We should defenitely unify the naming and also make the descriptions more understandeable.
