### ISSUE TITLE
[Config Manager] Options - COM_JOOMGALLERY_ADMENU_EXTENDED_CONFIG missing.

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#66]
![Screenshot 2023-01-03 183516](https://user-images.githubusercontent.com/110494397/210410579-a5a9c8ce-f7dd-477e-8928-a15949c73a7b.jpg)_DESC

**Comment by szepty-ziemi** [comment]
That's a known issue... also I think that setting currently do not have any effect.

**Comment by MrMusic** [comment]
I think this option will be removed in the future.
