### ISSUE TITLE
[FileManager service] Problem with images including a dot in the filename

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#68]
Please, can somebody test this!
In my tests, Original, Detail and Thumbnail were created successfully. 
But in Tab “Images”, no image will find.

**Comment by szepty-ziemi** [comment]
Hi, Alexander, to which PR your request apply? Or you mean main branch?

**Comment by AlexanderSupp** [comment]
Thanks for the hint. I've now tested both. Numbering yes/no. It's not because of that.

**Comment by MrMusic** [comment]
I suspect the problem with the missing images is because you are trying to upload to a subdirectory. Probably there is a problem with the directory structure, maybe it is related to this problem: https://github.com/JoomGalleryfriends/JG4-dev/issues/44  
As long as this is not solved, you should only work in the top category level.
Furthermore, the created file name depends on whether 'Original filename' is activated in the configuration or not. Although this option is intended for setting the image title in the mass upload, it also plays a role here.

**Comment by AlexanderSupp** [comment]
In my case, it was not the directory.
File Name in the DB Table  was: 20160316162440.jp_20230118_1788119348.jpg
File Name in the Directory was: 20160316162440jp_20230118_1788119348.jpg
The “.” was the problem.
I changed the DB-Table and everything works.

**Comment by AlexanderSupp** [comment]
"Original filename" in my Global Configuration is marked red and set to no.

**Comment by AlexanderSupp** [comment]
![Blumenmer](https://user-images.githubusercontent.com/110494397/215823611-42efbf19-01c3-4be0-b17e-c92841f5fa09.jpg)

Today I was able to reproduce this bug with the photo above.
Details of my config are here.

[DS214Play-20230131-Joomla-Installation.txt](https://github.com/JoomGalleryfriends/JG4-dev/files/10548796/DS214Play-20230131-Joomla-Installation.txt)

I got the same result with WampServer.
Can somebody try this with my picture and config.
Image processing with GD Lib.
Image Title "Blumenmer.jpg-20230131" (look at dot).

![Screenshot 2023-01-31 175307](https://user-images.githubusercontent.com/110494397/215830010-d0ae257f-7622-4792-9fd0-cae3e2fc1911.jpg)
![Screenshot 2023-01-31 175344](https://user-images.githubusercontent.com/110494397/215830023-1a5e7ee9-33e3-418c-ab4c-25be34daf6a4.jpg)
![Screenshot 2023-01-31 175418](https://user-images.githubusercontent.com/110494397/215830031-c1216bfe-dec5-4b6f-813a-9a80e692e3a6.jpg)
![Screenshot 2023-01-31 175436](https://user-images.githubusercontent.com/110494397/215830035-8af46c2a-8b4e-48dc-af44-c3903546e7f9.jpg)

Tested with current main branch on my Synology. Same result on my Wampserver-PC.

**Comment by Elfangor93** [comment]
Fixed in PR https://github.com/JoomGalleryfriends/JG4-dev/pull/86
