### ISSUE TITLE
Test Environments - Experiences

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#72]
I need help. This is the second time I've run into an error starting XAMPP/MYSQL. The first time, my action with delete and replace of the *.MAI files still worked. Now it doesn't work. Does anyone have any ideas how to get out of there.
Thanks.
[MySQLError-20230122.txt](https://github.com/JoomGalleryfriends/JG4-dev/files/10474963/MySQLError-20230122.txt)

**Comment by MrMusic** [comment]
Hi Alexander,

unfortunately, I also have this problem quite often. Probably when the notebook goes into energy-saving mode. The following has usually helped: https://community.apachefriends.org/f/viewtopic.php?f=4&t=81772#p275769
PS: php 8.2 is still quite new at the moment. i would personally stay with php 8.1.

Alternatively, I would recommend the 'Wampserver', which don't have these problems.

**Comment by AlexanderSupp** [comment]
Thank's for the Tipps. However, the measures mentioned in the link did not help me. Other measures were also unsuccessful. It amazes me how many users around the world have this problem and can't find a competent solution. Everyone is just poking around in the fog. I used XAMPP as suggested. Have now removed it from the system and will try »Wampserver« (a French variant?!).

**Comment by AlexanderSupp** [comment]
After the issues with XAMPP/MYSQL I changed my environments.
Primary now I use (1) Wampserver with mysql, PHP-Version  8.0.26. (i7-12700K, 32 GB mainstorage, SSD only)
Also, (2) my provider DomainFactory with mysql, PHP-Version 8.1.14
and (3) Synology NAS, DS214Play with DSM 7.1.  mysql, PHP-Version 7.4.30
(2)-Weakness, low transfer rate while uploading images.
(3)-Weakness, slow CPU, only 1 GB mainstorage
