### ISSUE TITLE
 Fix problems with image processor ImageMagick #74 - Merge was not successful

### ISSUE THREAD

**Issue by AlexanderSupp** [JoomGalleryfriends/JG4-dev#80]
Something is wrong – I have now the old status

**Comment by MrMusic** [comment]
@AlexanderSupp Which Branch do you use?
I did a test with the 'main' Branch and ImageMagick v6.9. x and upload works perfect.

**Comment by AlexanderSupp** [comment]
Bingo! I know the reason.
I was not sure about my branch, so I deinstalled JoomGallery and installed the latest main branch.
After that, it works.
Hmm.
Then I installed the latest JG4-dev-tus-server.zip.
And this will not work with ImageMagick upload.
It's a task for Manuel.
