### ISSUE TITLE
When joomgallery for joomla4?

### ISSUE THREAD

**Issue by ARTIS-MEDIA** [JoomGalleryfriends/JG4-dev#88]
When joomgallery for joomla 4? I want to migrate joomla 3 to joomla 4 and I can't because the gallery breaks. I have over 300 categories and I don't want to lose it.

**Comment by Elfangor93** [comment]
See corresponding thread in our JoomGallery forum:
https://www.forum.joomgalleryfriends.net/forum/index.php?thread/178-joomgallery-for-joomla-4/&postID=1596#post1596
