### ISSUE TITLE
Thumbnail for category cannot be selected

### ISSUE THREAD

**Issue by reni68** [JoomGalleryfriends/JG4-dev#89]
While testing for PR #86, I noticed that I can't (yet) select a thumbnail for a category.

I can't select an image because it's set to "Not Approved" ...?
![85_1](https://user-images.githubusercontent.com/126355001/229606021-d899bcf3-f865-400f-926a-7df287f178c1.jpeg)

But under images I see all images as "Approved"
![85_2](https://user-images.githubusercontent.com/126355001/229606076-f3bce427-fee1-4b2c-80a5-26ad5a919f89.jpeg)

**Comment by Elfangor93** [comment]
Your second screenshot is showing two not approved images. There needs to be a green thick in the "Approved" column marking an image as approved...

**Comment by reni68** [comment]
Sorry, I had misinterpreted that :(
