### ISSUE TITLE
[All content types] Titles containing only spaces should result in an error

### ISSUE THREAD

**Issue by eumel1602** [JoomGalleryfriends/JG4-dev#91]
In PR #86 I noticed that:
If I use an image or a category or a tag with only one or more spaces as a title, it saves it, but I can never edit the image again. Saving a e.g. Image with only one space should show an error from my point of view! / when I save a second image with one or more spaces, the system automatically adds a "(2)" and so it's clickable...
![bildschirmabgriff](https://user-images.githubusercontent.com/96334985/230558431-a58b6018-030f-4d40-9998-6736220a7c4c.jpg)

**Comment by reni68** [comment]
IMHO, titles that start with a space should also bring an error.

**Comment by szepty-ziemi** [comment]
We should follow Joomla approach, with the same notice:

![obraz](https://user-images.githubusercontent.com/60470150/231261953-4713e8b8-cc52-4a22-a109-308183b42add.png)

Also, Joomla allows to put any spaces at the beginning of the title without any error:

![obraz](https://user-images.githubusercontent.com/60470150/231262222-53ad63c7-9196-429e-8674-f21cadb121c0.png)

It allows to save them... but they are just not displayed on articles list or in frontend.

**Comment by togo-de** [comment]
Why not trim and check the title data before save? If the title empty after trim, return with an error or include a #NONTITLEGIVEN# string.

**Comment by Elfangor93** [comment]
Close this, since it is fixed with PR#176.
